### ISSUE TITLE
Species missing

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#108]
cypress carpet - common name of existing Thera cupressata

**Comment by kitenetter** [comment]
Another missing moth is Pale Brindled Beauty, common name of the existing Phigalia pilosaria. At the last UKSI update on the iRecord website we also had a problem with missing English names for moths, which @johnvanbreda subsequently fixed

**Comment by kazlauskis** [comment]
Caloplaca flavescens or it's synonym.
Early Bumblee is missing both as the common name and as Bombus pratorum.

**Comment by kazlauskis** [comment]
Peacock butterfly common name missing

**Comment by richardcomont** [comment]
For bumblebees, Bombus pratorum, vestalis, bohemicus and rupestris are all missing

**Comment by davidgenney** [comment]
Hi Karolis,
I have a missing species from the App and website to report:
Buxbaumia viridis NHMSYS0000309525 (I thought this had been added but doesn't seem to work now)

Also, so you know what we can do when the NHM list doesn't seem to be up to date? I tried to record the lichen Degelia cyanoloma  BMSSYS0000048975 but the NBN Atlas and iRecord force it to the old synonym Pectenia cyanoloma.

Thanks,

Dave

**Comment by kitenetter** [comment]
Hi @davidgenney , regarding changes or additions to the UK Species Inventory you can either contact Chris Raper direct at the Natural History Museum, or go via the NBN UKSI forum:
https://forums.nbn.org.uk/viewforum.php?id=16

**Comment by davidgenney** [comment]
Thanks @kitenetter, I'll discuss this with my British Lichen Society contacts and do this if they agree.

**Comment by kazlauskis** [comment]
Thanks @davidgenney, I will release a new app version for testing with an up to date UKSI list very soon now.

**Comment by kazlauskis** [comment]
powdered quaker is missing.

**Comment by kazlauskis** [comment]
Metriotes lutarea  is missing

**Comment by grahamcheckley** [comment]
Mother Shipton, Small Phoenix and Yellow-bordered brindle seem to be missing.
