### ISSUE TITLE
Important species suggestions

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#109]
A comment from a user:
> Can you please include a list or generator of particularly important (ie. under-recorded) species? Or a list of specific wildlife you deem priority please.

**Comment by kitenetter** [comment]
I think this would be hard to do in the generic app, as there will be many different ideas of what is important, and often under-recorded species are under-recorded in part because they are hard to identify. Probably needs a more project-specific or recording scheme specific approach.

**Comment by johnvanbreda** [comment]
An interesting idea at some point might be to explore the Pantheon dataset with a view to using it to provide suggestions of what to look for. Pantheon gives us information like habitats, resources used by species and assemblages, so the list entered for a site could be used to generate likely candidates of what else to look for. 
This needs careful thought though - wouldn't want it to pop up a suggestion to look for something that can only be ID'd with a microscope without a clear warning!

**Comment by kazlauskis** [comment]
No one has asked this since so I am closing this now.
