### ISSUE TITLE
Too many clicks to take photo

### ISSUE THREAD

**Issue by japonicus** [NERC-CEH/irecord-app#110]
@SK53 raised issue NERC-CEH/NYPH-app#42

Among other good points, he highlights the generally superfluous click needed to choose whether to use the camera or pick from a gallery.  I think that, when used in the field, the app should go straight to the camera (not to the gallery/camera menu).  It appears that this behaviour can be set through the cordova camera api by specifying CAMERA as the picture source.

**Comment by cubitmg** [comment]
Is there a way back to choose from a gallery picture if the default suggested is implemented? I can't seem to find a way. I think this may depend on what you are recording. It may be that some species groups the recorder has to snap a picture before it disappears and doesn't have time to get into the app, add a record/list, and then get to add a photo as it would have gone? Maybe have two icons from the record screen, but then that adds clutter!

**Comment by kazlauskis** [comment]
Yes, this is a tricky one. On iOS you can keep the device locked and just swipe the screen to the left to open up a camera and snap a photo to your gallery from where you can attach it to a record - so super efficient for opportunistic records (like mine 😄). But even then it isn't hard to create a record first and attach the photo from the gallery, so I feel it might be more useful for the majority of the users to jump right into the camera from the app home page.

**Comment by kazlauskis** [comment]
That's done now.
