### ISSUE TITLE
Subgeneric names causing problems

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#112]
From Matt Smith of BWARS:
With the app, the name Bombus pratorum does not appear in the list of available names when searching using "Bombus"
For two addtional Bombus species, Bombus ruderatus and Bombus bohemicus, the sub-generic name is included in the list of species pulled up when searching Bombus.  This means name searches for these two species do not work correctly as the sub-genic name means you cannot pull up Bombus bohemicus.  Although the names are in the list you have to search the list for them and users may think that the name is "missing" if they cannot find it with a binomial search.
 
Searching the common name "Early Bumblebee" does not find Bombus pratorum.

**Comment by kazlauskis** [comment]
Thanks, I will look into this.

**Comment by kazlauskis** [comment]
Bombus pratorum missing #108
