### ISSUE TITLE
Date field behaving oddly

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#114]
If I enter a date, and then lock the field, the back arrow to return to the main record details become disabled. I can use the phone's back function to navigate, but the app's back function seems to stop.

Also, having entered a date, and then locked it, and then used the phone's back function to go back the main record list, when I try to add the next record the date has become locked on to 1/1/1970.

**Comment by japonicus** [comment]
I think this is a re-occurrence of a bug I fixed in the NYPH app: https://github.com/NERC-CEH/nyph-app/commit/f4bc985561210a9eb3bf49c13dbd098ef3766396

src/records/attr/controller.js is missing an include for the date helper, referred to by the date-locking code.
