### ISSUE TITLE
Link to Activities no longer working?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#120]
I don't seem to be able to find any Activities on my phone any more, not sure if that is an issue with the app or at the iRecord end of things.

**Comment by johnvanbreda** [comment]
I can still see some activities on my phone - have you got any active activities that are not expired? Have you tried the refresh button?

**Comment by kitenetter** [comment]
Hi @johnvanbreda as far as I can see there are four current activities that are set up for use with the app in my activities list on iRecord, but on the phone app the only option I have if I go to the Activities settings is the pre-selected "Default". The refresh button appears to work (i.e. it briefly fashes off and on again) but no activities appear in the list.

This issue was raised yesterday by another user who had set up an activity for mobile use but could not get it to appear on their phone.

**Comment by johnvanbreda** [comment]
@kitenetter - on further investigation I've realised the activities I can see are actually not my up to date list. The Garden Bioblitz 2017 activity which I joined the other day is not appearing. Refresh does something, but I am not sure it is actually refreshing.

@kazlauskis I've put some debug code on the warehouse and is looks like the activities refresh button doesn't actually load the report, even though caching is disabled as far as I can see. I've also put a debug line in the mobile auth module on the iRecord server and it does not seem to be calling mobile/report when I click Refresh.

**Comment by johnvanbreda** [comment]
@kazlauskis I thought I'd have a go at debugging this (since the Garden Bioblitz is starting on 3rd June) but found that I can no longer run grunt dev without errors, even without a full refresh following the instructions in the readme. The first error is a circular dependency between src/app.js and src/common/controller.js as both these files refer to each other.

**Comment by kazlauskis** [comment]
@kitenetter I will look into this issue

@johnvanbreda the circular dependency should be alright as they were there all the time before I have fixed them now. But there must be something else that your build errors, can you post me your build logs please?

**Comment by johnvanbreda** [comment]
@kazlauskis I've attached my grunt dev output. I've only checked the first error but it does look like a real error - the app.js file is imported in src/common/controller.js and the app.js contains an import of common/controller.js.
[grunt-dev-output.txt](https://github.com/NERC-CEH/irecord-app/files/1010868/grunt-dev-output.txt)

**Comment by kazlauskis** [comment]
Looks like the app is requesting the reports through http protocol and the redirect to https upsets it somehow. I will try to temporarily disable https redirect for the /irecord/mobile/reports path so that the existing users could load the reports using our apps again.
