### ISSUE TITLE
Link the users to other BRC apps

### ISSUE THREAD

**Issue by DavidHepper** [NERC-CEH/irecord-app#122]
We're getting quite a few dragonfly sightings on the generic iRecord App but would much prefer these to arrive via the Dragonflies App. This would give us much more useful detail, especially of life stage but is made even less likely because the logo for the iRecord App is... a dragonfly. Users think they are already in the right place.
It would be easy to update the text at https://irecord.org.uk/app/ to make people aware of the separate Dragonflies App.
As a further enhancement, could the iRecord App show a prompt, even _after_ submission of a dragonfly record, flagging up the Dragonflies App as a better tool?
This could be extended to other groups, such as those with apps by Natural Apptitude.
David

**Comment by kazlauskis** [comment]
To add to this, we are currently adding an advanced 'Surveying' mode to the app, so potentially we could migrate the dragonflies multi-record form to this app.

**Comment by DavidHepper** [comment]
It seems that Lichens and Dragonflies are the only non-native Apps listed at http://www.brc.ac.uk/apps and all the others come from the Android or iOS stores. It would be great to replace our current app with tailored 'survey' features within the generic iRecord App, so long as this doesn't make it overly complex for new users.

**Comment by kitenetter** [comment]
As far as I'm aware this is no longer an issue - closing.
