### ISSUE TITLE
Locked grid reference doesn't carry forward to subsequent records in 2.0.0 beta

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#123]
A grid reference taken in the field from GPS and then locked doesn't carry forward to subsequent records.

If the location is taken using the GPS and then locked, returning to the Edit screen removes the locked symbol.

If the location is taken using GPS and then refined using the map and then locked, returning to the Edit screen maintains the lock for that record; but adding a new record fires the GPS and overwrites the "locked" grid reference of the new record.

**Comment by kazlauskis** [comment]
Hi, oh I see, this should be fixed then. Thanks!

Also, regarding the missing species in the list mode - it should be clearer that the list functionality is only for the plant recording at the moment (filters the vascular plants only). We will add more  species support in the future.

**Comment by japonicus** [comment]
I think that locking of GPS-derived grid-refs (if allowed at all) needs real caution. I'd see trustworthiness as a <em>major</em> advantage of device-GPS'ed grid-refs.  For that to work the GPS reading needs to be a live one and allowing it be locked while still treating it as a GPS reading is actively harmful to data quality.

What is the use-case for allowing GPS to be locked?  The risk is that would lead to invalid and over-precise grid-refs to be spuriously assigned to subsequent records.
