### ISSUE TITLE
Location display occasionally changes from grid reference to lat long in 2.0.0 Beta App

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#124]
Although I've set the app to display OS grid reference it has hopped from this to latitude and longitude on a couple of occasions during beta test.

It happened again this morning with my first record of the day.  I'd cleared all of my previously submitted records and had the app set to use and show grid reference.  Latitude and longitude appeared as the location and refreshing the gps had no effect on the display.  I fixed it by touching the map, selecting but not locking a 10 metre square location.  After that all of the subsequent records came up with a valid grid reference.

**Comment by kazlauskis** [comment]
Thanks, I wonder how did this happen. The app uses lat/longs for sea-records, this could affect some islands I guess. You weren't fishing :fish:, were you? :smiley:

**Comment by grahamcheckley** [comment]
Quite a number of the places where I record are partly sea at least at a 10km square level, e.g. NT27 and east along the coast...
