### ISSUE TITLE
Bees are omitted from my top 10 species data entry list in the 2.0.0 beta iRecord app

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#125]
My top 10 species list doesn't match the list shown under statistics.  My statistics top species includes 3 bee species that are omitted from my top 10 for data entry, namely Common Carder, Buff-tailed and Large Red-tailed Bumblebee.  The previous version of the app had the same problem.

**Comment by kazlauskis** [comment]
Hi, are you talking about the taxa search page suggestions? Or are those species also missing from the Info->Statistics page too? Thanks!

**Comment by grahamcheckley** [comment]
These bees are present on the Statistics page but are missing from the taxa search page suggestions.

**Comment by grahamcheckley** [comment]
All of the top 10 are now shown in the iRecord app but the sequencing is not correct.  Common Carder, for which I have the most records, is shown last in the list rather than first.  I'll close this issue and open a new one.
