### ISSUE TITLE
Submitted record missing Recorder details

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#128]
Record No. 5482874 has appeared on the verification grid with no Recorder details showing.

**Comment by johnvanbreda** [comment]
Looking at the data, I'm pretty sure no recorder details came in from the app when it was submitted. @kazlauskis any thoughts?

**Comment by kitenetter** [comment]
Not sure if this is the same issue, but just had this report via the iRecord inbox:
"I recently upgraded to the new version of the iRecord app and unfortunately forgot to log back into my account, causing some of my records to be submitted anonymously. I was wondering if it’s possible to link these back to my account? The record ids in question are as follows:
5358879 to 5358888 inclusive
5423071"

It appears that the app is allowing records to be sent while not logged in - the above examples are showing as input by admin, core.

**Comment by kazlauskis** [comment]
Hi all, yes I can confirm that the app allows to send existing records without a login. I think this happens when user clicks 'Send All' without being logged in. Also, possibly if the user has logged out but still has some records marked for submission but not yet submitted. All these records are attached to the admin account at the moment. I will investigate this further this weekend.

**Comment by JimBacon** [comment]
I've seen various messages about difficulties logging in to the new app. Don't know if this is related but I'm just grappling with problems logging in from a different app to a different server. I'm still testing from a browser mind you. My difficulties are to do with cross-origin requests. 

Firstly, there are pre-flight tests carried out on the Ajax request which are sent as an http OPTIONS request. The Drupal 7 API module will respond to this if it gets the request. I had to add OPTIONS as an allowed verb to the PHP handler in IIS for it to work. (PUT is not allowed by default either.) Now I get an Access-Control-Allow-Origin = * in the response but hit a second problem. The Drupal 7 API module does set Access-Control-Allow-Headers = Authorization but is omitting x-api-key.

Does the iRecord App need cross-origin support to work? How is this enabled on the web server? I note that if it involves setting the verbs for the PHP handler these could be at risk every month when Biren updates PHP.

**Comment by kazlauskis** [comment]
Hi @JimBacon, the cordova webview doesn't need the CORS headers to make the cross-domain requests, so it shouldn't be a problem. To enable this on you browser install the [Chrome CORS plugin. ](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi)

**Comment by JimBacon** [comment]
Thanks. You may still like to check out the password reset from the app though as it uses http PUT and I  think the iRecord PHP handler will reject that.

**Comment by kazlauskis** [comment]
Yes, I think @BirenRathod has allowed the PUT on dev and live iRecord.

**Comment by JimBacon** [comment]
The app goes "Yikes!"

**Comment by kazlauskis** [comment]
Oh, OK, then something has changed then. @BirenRathod, is the PUT still enabled on the live iRecord?

**Comment by BirenRathod** [comment]
I just checked for iRecord website and it is not enabled. I just enabled it. I think this is because of the PHP upgrade.

**Comment by JimBacon** [comment]
Password reset from app now working.

**Comment by kazlauskis** [comment]
Great, thank you both.

**Comment by JimBacon** [comment]
Here is another route by which anonymous records can be submitted through the app.
1. New user registers. Following registration the user is automatically logged in to the app.
2. User ignores or never sees activation email.
3. User submits records.
These records are sent but are anonymous. 
It seems to me that this is very likely to arise.

**Comment by kazlauskis** [comment]
Yes, I should investigate this too. Thanks Jim.

**Comment by kitenetter** [comment]
Following discussion at #143 I think we may have another route for anonymous records (if I've understood correctly):

1. User has app successfully linked to iRecord account
2. User edits their email address on iRecord
3. User submits records from app, which fails to find the email address it is looking for - records end up being anonymous

**Comment by johnvanbreda** [comment]
2 solutions spring to mind:
1) The app should submit against the warehouse user ID rather than the email address, as the latter is transient.
2) Or, if using the email address, then whichever bit of code is responsible for mapping this to a warehouse user ID before saving the record must also look in the user_identifiers table, where we track multiple email addresses per account.

**Comment by kazlauskis** [comment]
We have moved to the direct warehouse survey upload (JWT authentication) so this shouldn't happen anymore.
