### ISSUE TITLE
Location name and GPS info not being saved on record.

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#129]
When adding records to the app, the first record of the day appears to work ok, I can complete the entire record including the Location Name and the GPS location.

With subsequent records, the GPS location works ok, but I am unable to retain the location name on the record.  After completing the location name and moving back to the main Record page to complete other fields, the Location Name is not retained.  Instead, the app displays "yt" in place of the location name.  The same error is produced on subsequent records, or if I go into one of the erroneous records and try to edit or re-enter the location name.  At this point the GPS location is still on the record.

If I exit the app and then restart it, all the affected records have lost both the "yt" from the location name and the GPS location of the record.  This means I am left with a list of records with no site name or geo-location - see attached screenshot.

The problem appears to be intermittent - I cannot seem to replicate the issue on demand.
I have had a very similar / identical problem with the iRecord app in the past but hoped that the new release would improve things, but this does not seem to be the case.

**Comment by kazlauskis** [comment]
Thanks. What is your operating system and version? I assume the app version is 2.0.0, right?

**Comment by MNSmith** [comment]
The App is v1.2.1 - This is a recent download from the App store - i cannot seem to download V2.0

**Comment by kazlauskis** [comment]
What is the Android version you are running?

**Comment by SK53** [comment]
I'm seeing the same problem with the latest version (downloaded from appstore on Saturday). I have not experienced this with earlier iterations (eg. the NYPH app). Appears to be v2.0.0 (3) (at bottom of About splash screen). Android version 5.0.2.

**Comment by SK53** [comment]
Comparison screenshots of iRecord (green stripe at top) & NYPH (blue stripe) used to record the same plants on 12th October:
![screenshot_2017-10-12-14-10-43](https://user-images.githubusercontent.com/5452818/31716017-14ce059a-b3fe-11e7-8cde-baf2377b8da1.png)
![screenshot_2017-10-12-14-11-22](https://user-images.githubusercontent.com/5452818/31716033-22c83472-b3fe-11e7-9cb2-214add8db4c2.png)

**Comment by JimBacon** [comment]
I can partially but consistently replicate this on iPhone (iOS 10.3.3) with iRecord App 2.0.0 (3)

1. Reset app
2. Log in
3. Add first record
4. Edit location. Grid ref has been obtained by GPS. Add location name and lock it.
5. Add more records. They all have a grid ref and location - no need to edit.
6. Close the application.
7. Reopen the application.

The first record still has a grid ref and location name. Subsequent records have the same location name but no grid ref. This does not arise if I edit the location name for each record rather than use the lock.

**Comment by SK53** [comment]
I think I have only used the app with location name locked. I am mainly
recording at the monad level, although value the finer level of detail.

**Comment by kazlauskis** [comment]
Good stuff guys, I could replicate the problem too. Will fix this asap!
