### ISSUE TITLE
Building the app according to README.md

### ISSUE THREAD

**Issue by johnvanbreda** [NERC-CEH/irecord-app#130]
I've just attempted to build the app following the instructions in README.md. I'm running NodeJS v8.4.0 which is the latest stable version. All OK up to the point where I run grunt dev, then the script aborts due to errors. I've attached a doc with the grunt dev output.
[grunt-dev-errors.docx](https://github.com/NERC-CEH/irecord-app/files/1246104/grunt-dev-errors.docx)

**Comment by kazlauskis** [comment]
Gee, 65 pages of red text. Looks like there is an error :D The instructions I believe are correct.

`Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime` this one is the first time I have seen.

The missing BIGU is something @JimBacon and I have fixed for Linux environment which looks like it has broken the Mac OS now. I will fix it once I find some time.

**Comment by johnvanbreda** [comment]
Thanks - useful to know which message was unique to me. I found this link https://github.com/sass/node-sass/issues/1764 and can confirm that running the following before grunt dev fixes it:
```
npm rebuild node-sass
```
I am now in the situation where the BIGU errors are the only ones preventing the build.

**Comment by JimBacon** [comment]
I had problems with node-sass too. Try `npm rebuild node-sass` to see if that helps. I know I downgraded my version of node when I was trying to build things initially. I'm currently on 6.11.0. That may not have been necessary.

I also had problems with BIGU. It was just an aggravating case-sensitivity issue. Moral: never use caps in file names. Check your /node_modules folder. It was installed in BIGU/dist/BIGU.js for me, hence https://github.com/NERC-CEH/irecord-app/commit/7a2709ec1027509296837bf2e569a45b3dd0b4ad

**Comment by kazlauskis** [comment]
Yes, we should lowercase it all, I will push the fix.

**Comment by johnvanbreda** [comment]
I don't actually have a bigu or BIGU folder in my node_modules - I'm not sure why. Hence I suspect the problem is not just the case sensitivity issue Jim had, but actually some problem with package.json and npm install. I've just tried npm install kazlauskis/BIG, then grunt dev and it seems to have worked, though there are warnings such as 
```
WARNING in ./~/bigu/dist/BIGU.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

**Comment by JimBacon** [comment]
Perhaps your modules are installed differently or maybe the node_modules folder is populated during build - I don't really know how it works. The error message very definitely suggests to me that you already had the module installed but that you now have it available with different case settings that have allowed it to build.

**Comment by kazlauskis** [comment]
I will fix this up for both Mac and Linux this weekend.

**Comment by kazlauskis** [comment]
Hi both, this should be fixed now. Please pull the `develop` branch and try building it. First, I suggest running `npm run clean` to remove previous artifacts.

**Comment by johnvanbreda** [comment]
I agree - the develop branch now works. Thanks.
