### ISSUE TITLE
Missing or incorrect API key.

### ISSUE THREAD

**Issue by rich-frost** [NERC-CEH/irecord-app#131]
Hi guys,

I'm trying to run your app locally and have added the Chrome extension for CORS and trying to test the login. It appears to connect, but gives me a 401 for a missing API key: {"errors":[{"status":"401","title":"Missing or incorrect API key."}]}

Is there a way I can go about getting an API key?

Long term, I'm trying to create a version of your app but connect to a different Indicia warehouse - I've not yet figured out how to connect to this warehouse or whether I can register an API key somewhere?

Appreciate if you're able to point me in the right direction.

Cheers :)

**Comment by kazlauskis** [comment]
Hi,
Yes, you can connect it to your own warehouse, but only indirectly as this is the current setup we have. The app communicates to a Drupal site using the [drupal-7-module-indicia-api](https://github.com/Indicia-Team/drupal-7-module-indicia-api) which allows to generate an API key. So a setup of an Indicia Warehouse and a Drupal site (iform + indicia-api modules) should work.

**Comment by JimBacon** [comment]
The way we work is to have an intermediate website between the warehouse and the app. We have been using Drupal for this. There is a Drupal module, https://github.com/Indicia-Team/drupal-7-module-indicia-api, which creates API keys and provides the interface for the app. The Drupal site will also need the IForm module, https://github.com/Indicia-Team/drupal-7-module-iform, and the EasyLogin module from https://github.com/Indicia-Team/drupal-7-module-indicia_features.

**Comment by JimBacon** [comment]
Ha ha. Double answers @kazlauskis. Looks like we agree quite well :-)

**Comment by rich-frost** [comment]
Wow, appreciate the quick responses guys! Thanks so much, will take a look at that module.

**Comment by rich-frost** [comment]
Do you know if there is any ideas around creating a Drupal 8 equivalent of this module? Just realised our site is using 8! I could look at the upgrade path (https://www.drupal.org/docs/8/converting-drupal-7-modules-to-drupal-8); though am not a Drupal dev unfortunately

**Comment by JimBacon** [comment]
As an open source project there is, on the one hand, no telling what might be happening. On the other hand, I think we (the Biological Records Centre at the Centre for Ecology & Hydrology) are the only people who are using it. The guys from Natural Apptitude seem to have gone off in to a world of private development although they created the original mobile authentication module. From our perspective, assuming our design philosophy doesn't shift dramatically, we would do a Drupal 8 version as and when we needed it. I can't see us needing it very soon.

**Comment by rich-frost** [comment]
OK no problem, I may take a look at creating the module then based on your v7.

**Comment by JimBacon** [comment]
That would be great and I would gladly accept a pull request if you should do so. There is a D8 version of the IForm module and the Easy Login module already available.

**Comment by rich-frost** [comment]
@JimBacon @kazlauskis - not sure the best place to ask this; but am almost finished creating a D8 version of the Indicia API module though having trouble creating the route for the /api/v1/reports/% endpoint. D8 routing seems to work slightly differently and I'm yet to find how to handle %. Is there a standard format for the reports?

I notice in the Postman docs that the example URL is /irecord7/api/v1/reports/library/taxa/filterable_explore_list.xml - is library/taxa/ dynamic or is that always fixed? I'm new to a lot of this terminology and how it all works but just trying to work out the best way forward.

I could create a route in one of the following formats:

/api/v1/reports/library/taxa/{reportId} OR
/api/v1/reports/{param1}/{param2}/{reportId} OR
/api/v1/reports/{full-path} <---- I need to dig a bit deeper if this is needed :)

**Comment by kazlauskis** [comment]
Hi @rich-frost thanks a lot for your work on this. I would say that with the v1 it should be backwards compatible, so keep it {full-path}. The `full-path` is an identifier (mapped path) for the report sitting somewhere in the warehouse, so even if you want to change the formatting for it, I think, the path should still directly map the report on the warehouse, especially since the new warehouse REST API itself (part of warehouse) runs reports using similar URL schema
`INDICIA_WAREHOUSE_URL/index.php/services/rest/reports/library/occurrences?param1=1`

I would be better if you created an issue and moved this discussion to https://github.com/Indicia-Team/drupal-7-module-indicia-api where this topic mostly belongs.

**Comment by JimBacon** [comment]
Hi @rich-frost. Your comment to which Karolis replied on 31st Oct, has disappeared. However, I remember you saying you had almost finished a D8 version of the Indicia API module. I was wondering how you were getting on now.

**Comment by rich-frost** [comment]
Hi @JimBacon - yes I managed to create a D8 version at the end of last year. Repo can be found here: https://github.com/rich-frost/drupal-8-module-indicia-api

I've installed it on 1 website so far and am currently testing the full integration.
