### ISSUE TITLE
Vice-county information in grid square mode is not propagated to record edit screen

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/irecord-app#132]
Vice-county information in grid square mode is not propagated to record edit screen (Plant Card mode), although does appear in record overview.

**Comment by kazlauskis** [comment]
Thanks, are you saying that you would like to see the name of the vice county on every record in the list?

**Comment by sacrevert** [comment]
No, what I am saying is that when you edit records made via the plant card on the iRecord website, all the fields are filled in (e.g. status etc.) except for the vice-county. I'm not sure what would happen if one re-saved the record within the website (would the VC disappear because it has been left blank?) Anyway, as far as I understand it it seems to me that the records should have the entered VC filled in when one goes to edit a record on the website.

**Comment by kazlauskis** [comment]
Yes, that is correct, the VC should be displayed in the form as well. I will check this up.
