### ISSUE TITLE
Training mode: working?

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/irecord-app#134]
Does training mode work? I submitted records through the app in training mode, and they appeared in my normal irecord account without any sign that they were made in training mode.

**Comment by kazlauskis** [comment]
Have you selected the training mode before or after the record has been created on your device? ie. do you see a black band on the left of the record that you have submitted?

**Comment by sacrevert** [comment]
I think before but I will check. I have deleted the records/lists from my device now.

**Comment by kazlauskis** [comment]
I have tested this just now and it works on my device. Please try it out again with the training mode turned on before creating records and let me know if this happens again. Thanks!

**Comment by kazlauskis** [comment]
I have found some inconsistencies with the functionality and created a new issue Indicia-Team/drupal-7-module-indicia-api#16
