### ISSUE TITLE
Don't show non-training records in training mode

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#137]
And vice versa. The training mode should be a more sandboxed environment.

**Comment by johnvanbreda** [comment]
Just to clarify for consistency with iRecord. If training mode is enabled, then any record submitted should have the training flag set to true. Any reports which include occurrences should filter to only include occurrence records where training=true. When training mode is disabled (default) any record submitted should leave the training flag to it's default state or set it to false. Any reports should only show records which have training set to false.
The "filterable" reports which feature standard parameters should all support this flag out of the box.
