### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by rich-frost** [NERC-CEH/irecord-app#138]
Hi,

I'm trying to build your app for android, running `grunt cordova:android`

With my Google Play account I had opted-in to use Google Play App Signing; does your tooling support this; or is it just for manual signing?

Reading through your aliases grunt config; the android build runs cordova_android_build and cordova_android_build_old - is this correct?

Am getting some errors, which I think are around double signing of the APK, and wondering whether this is the issue or something else I've done.

```
    'cordova:android': [
      'prompt:keystore',
      // new
      'cordova:_prepAndroid',
      'replace:cordova_config',
      'replace:cordova_build',
      'exec:cordova_android_build',

      // old
      'cordova:_prepAndroidOld',
      'replace:cordova_config',
      'replace:cordova_build',
      'exec:cordova_android_build_old',
    ],
```

**Comment by kazlauskis** [comment]
Hi @rich-frost, yes we are signing the builds locally. If I were you, I would remove all the old cordova build tasks from this as this should simplify the build and, also, you might not want to support old devices.
```js
'cordova:android': [
      'prompt:keystore',
      'cordova:_prepAndroid',
      'replace:cordova_config',
      'replace:cordova_build',
      'exec:cordova_android_build'
]

`
