### ISSUE TITLE
Dynamic attributes

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#14]
Different species groups require different data to be recorded, so putting them all under one standard form is not right. We should have different attributes and separate terms lists for the attributes dependent on the type of organism entered (e.g. for a plant, the number ranges are different than an insect).

**Comment by steveblain** [comment]
Are dynamic attributes coming for any other taxa other than odonata? It would be great to implement them for other taxa that already have bespoke survey forms in the iRecord website, such as moths:
https://www.brc.ac.uk/irecord/enter-moth-sightings

**Comment by kazlauskis** [comment]
Hi @steveblain, thanks for the question, the app currently supports dynamic attributes for odonata, bryophytes and butterflies. @DavidRoy is best to answer which other groups we should add in next.
