### ISSUE TITLE
Dynamic attributes for odonata

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-app#142]
Feedback on demo:
http://irecord-app.herokuapp.com/#samples

Occurrence attributes (e.g. Em - ID 499 on live, Ad, Co, La etc) should enable numbers to be entered, as well as selecting a number range category from a drop-down list.

reference to #14

**Comment by kazlauskis** [comment]
Thanks, this one is complex though. It was done for the casual record's number attribute - managing two different types (a simple number and a list of values) as if it was one attribute. But this has created a lot of custom code to manage this differentiation. I will see if I can refactor the code to make this functionality more manageable.

**Comment by DavidRoy** [comment]
I can see this is complex.  Aren't the occurrence attributes (Ad, Co, Em etc) text values?  One short-term fix is to either submit a range e.g. ("1-5") or a number as text (e.g. "5")

**Comment by grahamcheckley** [comment]
The lack of a facility to enter a precise count is still an issue on the beta test release 3.0.0 (4).  As a result the dynamic attributes for odonata aren't consistent between the iRecord app and the BDS dragonfly import facility.

**Comment by kitenetter** [comment]
As far as I'm aware the app is correctly handling Odonata attributes now - closing.
