### ISSUE TITLE
Records going missing

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#143]
A user reports that the records she has submitted via the app for 2018 are not appearing in her iRecord view of her records.

She has recently updated her email address on her iRecord account in the website - does that have any implications for the link from the app to her iRecord account? Should we be providing any advice for users who need to edit their email addresses?

Or could it be another example of the bug referred to here - do we have a fix yet for that bug?:
https://www.brc.ac.uk/irecord/node/7147

**Comment by kazlauskis** [comment]
Hi @kitenetter, this sounds related to this one?
https://www.brc.ac.uk/irecord/node/7186

**Comment by kitenetter** [comment]
@kazlauskis yes, that is the same issue and indeed from the same person - you and @johnvanbreda are way ahead of me! I picked up the enquiry from the iRecord emails inbox and hadn't realised it was also in the forums. Hopefully John will have the solution.

It would still be useful to know if we need to provide any advice to app users about what they should do if they change their email address on their iRecord account.

And is the other bug now fixed?

**Comment by johnvanbreda** [comment]
Hmm - I've had a look on the warehouse and although Rachel does seem to have a couple of spurious accounts, her iRecord account is still linked to user ID 700 and that is the only one with any records linked to them for the iRecord website ID (which the app also uses). I would like to know what user ID the app is now submitting her records under so I've asked for an example record - as I can't see any of her records for 2018 by filtering for her name.

**Comment by kazlauskis** [comment]
@kitenetter No worries. What happens is that the app retains old user email and tries to submit a record which is then attach to an admin account because such the email is not attached to any user. It is very much linked to the #128. 

@johnvanbreda Unfortunately, it is the admin account. Sorry this should be fixed in the next few days. Let me know if you required help chasing up the records.
