### ISSUE TITLE
Edit Locations window requires amending

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#145]
If you go to amend location details, the "Favourite" text is partially overlain by the "Favourite" slider.

It would be useful to have a larger display for the location text here if possible.

![image](https://user-images.githubusercontent.com/18451743/37538871-e757ea60-2949-11e8-9778-bdc71826e39c.png)

**Comment by kazlauskis** [comment]
Well spotted, thanks, I will fix this.
