### ISSUE TITLE
Help text - lock an attribute.

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#146]
Looking the the help text for "lock an attribute", I think there is some possibility for confusion here as the text reads in a slightly convoluted manner.

Current text:   

You can lock record attributes like date, location, number etc, which will preserve your current attribute value for the subsequently added records.
To lock an attribute click on the lock  button in the attribute edit page header. This will change the symbol to locked  both on the button and next to the attribute. 

Note: locations acquired through GPS can not be locked. Also, running the GPS on a record that has a locked location will overwrite the location with the newly acquired GPS position but will not overwrite the existing lock, so subsequent records will still have the initially locked location.

Could I suggest the following amended text instead - changes & additions in bold.

You can lock record attributes like date, location **name**, number etc, which will preserve your current attribute value for the subsequently added records.
To lock an attribute click on the lock button in the attribute edit page header. This will change the symbol to locked both on the button and next to the attribute.  To unlock, click on the lock button.

**Note:  For a location, only the location name can be locked, not the GPS value.  As you move about, the GPS value will change.  This will allow recording of different GPS values within an named area while keeping the location name the same.  To change to a new location name the location will first need to be unlocked.**

**Comment by kazlauskis** [comment]
Great, thanks a lot, I will correct the texts. If you see any more places (both texts or functionality) where we could make it clearer then please let us know.
