### ISSUE TITLE
5 digit "Recorder" style taxa search

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#147]
At present the app offers 3 shortcuts for searching for a scientific name.

Could we please have the older 5 digit "Recorder" style format added to this list as I find this by far the easiest way of looking for species.

Eg _Puffinus puffinus_  = "pufpu"
_Bombus pascuorum_ = "Bopas"

Thanks.

**Comment by DavidRoy** [comment]
I'd support this request.  Can you confirm this is 2+3.  Therefore, should it be:
Eg Puffinus puffinus = "pupuf" not "pufpu"

**Comment by MNSmith** [comment]
Probably a good job I don't record seabirds very often.......

This is 2 Generic and 3 Specific - PUffinus PUFinus    / BOmbus PAScuorum

**Comment by johnvanbreda** [comment]
That's correct - 3 generic + 2 specific is how Recorder implements this, as does the iRecord website. The cache_taxon_searchterms table already contains all the abbreviations.

**Comment by MNSmith** [comment]
Subspecies should have the same 3 generic + 2 specific code as the nominate species and should appear as a choice on the resulting species list - the Recorder would have to select which they would use.

**Comment by japonicus** [comment]
Hybrids would probably best match using the nothoname part:

e.g. _Carex flava x viridula = C. x alsatica_ would match as <pre>caral</pre>
though in practice I'm not sure if people would use that short-cut for hybrids.

**Comment by MNSmith** [comment]
As noted, iRecord has the "3+2" search facility present.  In the case of Carex hybrids described above 
_Carex flava x viridula = C. x alsatica_ would still be found by searching for "_Cafla"_.  I'm not suggesting adding any complications along the lines of requiring an additional set of letter combinations need to be generated to managed the nothoname example above - just that it would make using the app easier, the Recorder would still have to make a choice from a list. Continuing on the sedge lines, here is how iRecord currently handles another set of sedge species and hybrids with a "3+2" search.

![image1](https://user-images.githubusercontent.com/18451743/37674367-a685afd0-2c6a-11e8-8a59-7e52c28f4d02.jpg)

**Comment by japonicus** [comment]
I'd not checked how Recorder dealt with hybrids. As a solution for hybrids Matt's is viable and could be the better option if that's what Recorder users are used to - though I don't like it as it throws up lots of problems: Carex x alsatica could be expressed as:

Carex alsatica
Carex flava x virdula
Carex viridula x flava

More generally I think it would be worth investigating the optimal data entry format for taxa on mobile devices (in terms of minimal 'typed' characters and choices that fit on a small screen).  I think that most of the current data entry options are sub-optimal in that context. (seriously: the best option might be voice recognition - that ought to be pursued).
