### ISSUE TITLE
Search by common or scientific name only

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#148]
Would it be possible to have a setting allowing the user to search by scientific or common names by default please.  I tend to record most of the time using scientific names and have noticed some of the aculeate lists get a bit swamped by lots of recently invented "common names" which I am unfamiliar with, which slows down the process.

**Comment by kazlauskis** [comment]
Yes, that would be possible. I would imagine this setting living in the app settings page.
