### ISSUE TITLE
Add Favourite Location help text

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#149]
Editing a location allows the user to set the location to "Favourite".  What does this do?  I can't see any help text or explanation for this feature.

**Comment by kazlauskis** [comment]
Hi, this then sticks the location to the top of the list. This is just for the convenience, you can set some favourite locations that you use more often and these will be always at the top of the past locations list.

**Comment by MNSmith** [comment]
Ok - so we need to have some help text to explain this for users.
