### ISSUE TITLE
Action upon selecting species

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#156]
At the moment when entering a new record the app returns to the record list page after a species is selected. I can see why this is efficient in some circumstances, however in the majority of cases I find myself having to re-open the record to enter the metadata. Could there be an option to stay within the current record? Perhaps as a user setting?

**Comment by kazlauskis** [comment]
<img width="291" alt="screen shot 2018-04-10 at 20 42 08" src="https://user-images.githubusercontent.com/7383162/38579745-d3a9dcf2-3cff-11e8-8fbc-130e5e5f89d5.png">

Click on the pen button on the right, it acts as a shortcut to the newly created record edit page.
