### ISSUE TITLE
Species names are truncated making it hard/impossible to see what's been recorded

### ISSUE THREAD

**Issue by ColinHCampbell** [NERC-CEH/irecord-app#157]
Once entered, species/taxa with long names appear truncated on the form view of a record (e.g. an entry of 'Greater Butterfly-orchid' becomes 'Greater Butterfly-or...' and 'Platanthera chlorant...').

This can lead to you not knowing which taxa you've actually recorded - especially if you're entering common names.  For example, if you enter an observation by typing and selecting 'Fly Agaric' the record displays 'Fly Agaric' and 'Amanita muscaria var...'.  From this you can't tell which variety it has selected and I'm guessing that in some instances, where the name is very long, the truncation might also obscure the fact that the scientific name had a var or ssp in it at all (I think'Pink Waxcap' might be an example of this).

Even if you are typing scientific names the truncation might mean you don't notice if you've inadvertently selected the wrong taxa from the drop down list.

This happens on the latest live version of the iPhone app and the v3.0.0(5) beta version, but not on an Android phone (v2.01(2)).  I think the truncation is to 20 characters.

**Comment by kazlauskis** [comment]
Thanks, I will look into how this could be improved.
