### ISSUE TITLE
Locking location name not working

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#158]
Over the last few weeks or so, the app appears to have lost the ability to "lock and save" location names.

When first testing the app in the field I could add a record, enter a location name and then "lock" the name using the padlock icon.  When adding a subsequent record the app worked as expected and the new record had the locked site name auto-entered on the location page.  Locked names also appeared to be saved to a list of locations.

This feature is now not working.  If I add a record, enter the location name and "lock" the name, this is not carried forward to the next record entered and not added to a list of saved names.
Instead, the text in the "location name" field on the app defaults to "true".   To complete a record I have to re-enter the name again.  If I do so and lock it again I see the same issue, the name is not saved.

The app will let me upload a record with "true" as the location name.  When I look at this record on the iRecord web page, the location  name for this record is shown as "1".  If I want to correct this I have to manually edit the record.

I had similar problems with the previous version of the app.  I am using an Android phone.

![irecord app](https://user-images.githubusercontent.com/18451743/39662872-b9320ef2-5060-11e8-861c-9972e90e44fd.jpg)
![image1](https://user-images.githubusercontent.com/18451743/39662874-bd64aeee-5060-11e8-9ba2-36f0c32952e5.jpg)

**Comment by MNSmith** [comment]
As a follow up - I went back to a site where I had previously saved the site name via the padlock when the app was working correctly.  When I unlocked the location name field and began typing I was able to select the correct site name from the saved list and this name was retained in the record without problems.

**Comment by kazlauskis** [comment]
Thanks Matt, I will try to fix this issue.

**Comment by MNSmith** [comment]
Will the fix need me to reinstall the app to try it out?

**Comment by kazlauskis** [comment]
It depends if you have joined the beta testing programme and also your device settings. You should be able to just update to the latest (3.1.0) version right now if you are a tester, or later once it is public.

**Comment by MNSmith** [comment]
I am a beta tester, I noticed an update auto-downloading the other day so I will try out the new version.


Matt



-----Original Message-----
