### ISSUE TITLE
Output OS grid ref does not agree with GPS accuracy?

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#159]
If I enter a record directly into iRecord I can drill down onto the map and locate my record within a 10m box.   I used to be able to generate an 8-figure OS Grid reference as a result.  

Currently, both on iRecord and on the iRecord app, the displayed calculated output OS grid reference does not reflect the accuracy of the record.  Records located to 10m accuracy only produce a 6 figure (100m) OS grid reference.  This is actually quite frustrating as in the field you assume the app is misbehaving because you can zoom right into a location but the displayed OS grid reference does not change to a better resolution as you would expect from previous use of the system.

Particularly in light of discussions elsewhere on this forum regarding the accuracy level of GPS/ OS Grid refs (see #154 ) could we please have both the iRecord web pages and the iRecord app display the OS Grid reference to at least the location accuracy level - if it's 10m accuracy then I would like to see and appropriate 8 figure grid reference displayed.

**Comment by kitenetter** [comment]
As far as I'm aware this is no longer an issue so will close but let me know @MNSmith if you are still seeing this problem
