### ISSUE TITLE
Locking location name not working (2)

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#160]
A follow up up to #158.  The downloaded fix does not appear to have corrected the problem.  I still find that after entering a location name and "locking" the name, the name is not retained for use in the next record.

**Comment by kazlauskis** [comment]
Hi @MNSmith, let's try something. If you unlock (if currently locked) the location name, create a new record, give it a location name, lock it, and create a new record: which of the two new records' location names do you see in blue colour when viewing the records in the records list?

**Comment by MNSmith** [comment]
This is what I get on the screen if I follow your instructions and make a new record, lock the name then create a second record at the same location.

![screenshot_20180522-144131](https://user-images.githubusercontent.com/18451743/40590312-960e1420-61f4-11e8-9bbc-cbdcbf303177.png)

**Comment by kazlauskis** [comment]
Thanks, this last record with the missing location name but with a location - is the location also locked or was it assigned by the GPS / or manually by you?

**Comment by MNSmith** [comment]
The record with the red "no location name" was created using a "locked" location.  Previously I ceated a record where I unlocked the location name, entered the text "test location" and locked the location name.  When creating the next record the location field was locked but empty, resulting in the red text appearing.

**Comment by kazlauskis** [comment]
No one has reported this since so closing this now.
