### ISSUE TITLE
Some user data is cleared on low free space

### ISSUE THREAD

**Issue by steveblain** [NERC-CEH/irecord-app#161]
My version of the app forces me to login repeatedly if left idle for a while.  If I leave my app for a short while (a few minutes) it is fine - I can use another app then come back to iRecord and it retrains my log in details.  However if I leave it longer, more often than not, when I open iRecord it reverts back to the welcome splash screen, I have to log in again, and my stored locations have gone, however my previously stored records are still present.

iRecord version v3.1.1 (1)
iOS 11.4
iPhone 6
used 15.3 GB of 16 GB storage on my phone (which may have something to do with it!)

**Comment by johnvanbreda** [comment]
Just for info - using the following for comparison, I don't have this problem. iRecord has kept me logged in OK for around 1 month at this point:
iRecord version v3.1.1 (2)
iOS 11.4
iPhone 6
Plenty of storage free.

**Comment by ColinHCampbell** [comment]
I've had similar problems.  I had it a lot when using the latest test version so went back to version 3.0 (v3.0.0 (7)).  I was fine for a while on that but recently it regularly freezes (forcing me to close it an open it again) or it reverts back to the splash screen and logs me out as described by Steve.  Either way I have to login in at least every day - sometime multiple times if I'm doing a lot of recording.

iOS 11.4
iPhone 6
used 14.8 of 16GB (the issues seemed to start at a similar time to my phone telling me I was running our of storage, but I don't know if the two are linked).

**Comment by kazlauskis** [comment]
Yes, storage is the issue here. On iOS, if the storage is running low, the device will clear some of it's internal memory. In the past it used to clear the records as well, so we have moved it to another storage solution, now it might be the time to move the other user information, like login details and other settings to this storage as well. Thanks for reporting this.
