### ISSUE TITLE
Annoying autocompletion of Grid References

### ISSUE THREAD

**Issue by SK53** [NERC-CEH/irecord-app#169]
From time to time my phone fails to get a GPS signal, or I want to add a record once I get home. In these cases I usually want to type in the monad and then find the precise location from OS or Satellite imagery. However as soon as I type the first 4 characters it autocompletes to a hectad. Then trying to add the third digit it repeats the hectad name. So:

1. Type SK54, and it completes as hectad
2. Type an additional "3" and it becomes "SK54SK543"

If there is a pause between adding the first 3 characters & the remaining two It seems to work sometimes.

This is very much a minor irritation, but thought I'd report it.

**Comment by kazlauskis** [comment]
Thanks for raising this, is it iOS or Android that you're using? Most likely, this is something about how the phone autocompletes the input fields here. I will keep an eye on this. 

In the meanwhile, you might want to save a location as a favourite and use it when selecting a base location. To mark a location as a favourite - swipe past location to left and toggle the favourite flag, the past location will then stick to the top of the list.

<img width="197" alt="Screenshot 2019-05-27 at 10 35 48" src="https://user-images.githubusercontent.com/7383162/58411077-6708d980-806b-11e9-9d97-b8dab17671eb.png">

**Comment by SK53** [comment]
My apologies for not stating version & O/s. Android 5.0.2. app version 4.0.1(1).

Thanks for the tip which will help a lot.
