### ISSUE TITLE
Add +/- buttons to Abundance count

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#174]
From Mark Gurney: 

> Do people use the slider in the Abundance screen? This could be replaced with bigger + and – buttons.

**Comment by steveblain** [comment]
I never use the slider as it always seems too imprecise. I end up deleting the number and adding one more manually, but this is very time consuming and frustrating. I love the sound of bigger + and - buttons to change the count value.

**Comment by kazlauskis** [comment]
Thanks @steveblain.

**Comment by ColinHCampbell** [comment]
I agree with Steve - having bigger +/- buttons would be fantastic.  Also second that about the slider.  The hit and miss nature of it means I don't really use it.

**Comment by kazlauskis** [comment]
This is very useful. I will add the buttons.
