### ISSUE TITLE
Allow wildcarding for species name search

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/irecord-app#176]
This would be useful for when people forget or misspell the genus name. For example:
*hians
would return
![Picture1](https://user-images.githubusercontent.com/5985134/72724377-0ccd0380-3b7b-11ea-8571-b63f5dd0c983.png)

**Comment by sacrevert** [comment]
OK, I've just realised that this is already available in the format 
. hians
This seems a bit unintuitive, can we change the wildcard operator to * and remove the need for the explicit space (I note that ".hians" doesn't work in the same way).

**Comment by kazlauskis** [comment]
Thanks, what about just searching `hians` without the '*'?

**Comment by sacrevert** [comment]
Currently returns "no species known with this name"

**Comment by kazlauskis** [comment]
I'm sorry, I meant what if I simplified the functionality to allow searching species names without even having to substitute the genus as a `*` (star) or `.` (dot). Entering the `hians` would return you the `Xylographa hians`.

**Comment by sacrevert** [comment]
Yes, that would be great too. (So searching `hians` would return the full list of matches illustrated in the image above). Thanks!

**Comment by kazlauskis** [comment]
Thanks 👍 please keep sharing these ideas here, it's useful to hear what users would like to see next.
