### ISSUE TITLE
Make map available outside of occurrence record generation

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/irecord-app#178]
Map function is generally useful outside of recording. Make this available without having to create a record. This could take the place of "photo" icon on the front page of the new app (v5.0.0), seeing as photos are available within occurrence records anyway.
@kitenetter @DavidRoy

**Comment by kazlauskis** [comment]
I would also like that and to show all the records on the map. A question to everyone: how useful is it to have the functionality to first start a record with a photo? If it is worth keeping this, then I could look for some other places to add the map view.

**Comment by sacrevert** [comment]
I don't have a particular opinion about this.

**Comment by DavidRoy** [comment]
I would favour a map of records as a top-level option in the app.  Being able to start a record with a photo is useful but perhaps it is best put alongside the [+] button used to add a species, i.e. a camera icon could go alongside it as another option?

**Comment by kazlauskis** [comment]
I can't add anyting else to the bottom toolbar as there are 5 options there already, but if we want to keep the photo-first recording in there, then I could add the map view of the records next to the Pending|Uploaded tab at the top. How does that look to you?

<img width="318" alt="Screenshot 2020-01-20 at 19 39 56" src="https://user-images.githubusercontent.com/7383162/72753357-acf74c80-3bbc-11ea-9c72-605b99ed8c93.png">

**Comment by DavidRoy** [comment]
That works for me.  
@sacrevert does this work for you?

**Comment by sacrevert** [comment]
Presumably in this format you could also check/use the map before entering any records? It's nice to see the records on a map, but my main thoughts were simply around accessing the OS layer, and entering target grid refs, without having to create a record. So, if that is supported, both before and after making a record, then that's fine.

I suppose we should also think about the default extent. If a user keeps lots of records in the app, the what is the default extent of this map view?

**Comment by kazlauskis** [comment]
So the most useful feature for you @sacrevert would be to enter a gridref and see that as a square on the OS map without having to create a record first?

**Comment by kazlauskis** [comment]
Hi both, I have added a map view to the app (v5). At the moment, it only shows the records on the map but we could think of what other features we would like to see there. When I'll find some more time, I will add the ability to enter grid refs and toggle the layers. To see the map you have to go to settings and toggle `Experimental Features`. 

![Screenshot 2020-01-28 at 12.08.17.png](https://zube.io/files/nerc-ceh/3352dc253c995fb6095d90c4a23687e6-screenshot-2020-01-28-at-12-08-17.png)

**Comment by sacrevert** [comment]
Thanks Karolis. My only comment would be that it would be useful to be able to toggle the records layer, along with everything else. When using the map as a map it would be nice to have it as clear as possible of other information.

**Comment by kitenetter** [comment]
@kazlauskis is this still a live issue? I can't see the experimental features option in the current app.

**Comment by kazlauskis** [comment]
This is completed now. The map was moved to the records tab Pending/Uploaded/Map.
