### ISSUE TITLE
Extend 'plant survey' to include bryophytes

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-app#179]
for version 5 of iRecord app, extend the 'Plant Survey' to include bryophytes.  Requirement =
- species list extended to include two extra taxon_groups (moss, liverwort)
- enable dynamic occurrence attributes for bryophytes (moss, liverwort) if added to list
- enable taxon_group filter on 'plant survey'.  The sames as for the 'General survey'

**Comment by japonicus** [comment]
Might it also make sense to add lichens and fungi, as recording of those could also be amenable to a similar grid-square list based approach to recording? (this would require renaming the survey to a more inclusive umbrella term though)

**Comment by kazlauskis** [comment]
> species list extended to include two extra taxon_groups (moss, liverwort)

Sure, I will add the moss and the liverwort groups.

> enable dynamic occurrence attributes for bryophytes (moss, liverwort) if added to list

As for the dynamic attributes for bryophytes within the Plant survey, I would suggest waiting for the website to catch up with the app first. The `enter-vascular-plants` web form on iRecord is not matching the current plant recording on the App (occurrences missing Identifiers, Abundance and Sensitivity attributes on the website, added screenshots to illustrate) so users can't fully edit their own records. If we enabled the dynamic attributes for the Plant survey on the app, this would diverge much more and would also require a new type of web form (that allows taxa specific attributes). This new type of web form will be built by John for the General survey in the app and then we could adapt it to the vascular plants form. 

> enable taxon_group filter on 'plant survey'. The sames as for the 'General survey'

Sorry, not quite sure what you mean by this. Is it enabling species search filters for the Plant survey?
 

<img width="100" alt="Screenshot 2020-01-20 at 19 15 24" src="https://user-images.githubusercontent.com/7383162/72753640-550d1580-3bbd-11ea-8a5f-06aa5ba14d02.png">
<img width="1095" alt="Screenshot 2020-01-20 at 19 16 34" src="https://user-images.githubusercontent.com/7383162/72753641-550d1580-3bbd-11ea-88e4-c7091087d866.png">

**Comment by DavidRoy** [comment]
> enable taxon_group filter on 'plant survey'. The sames as for the 'General survey'

I mean a 'FILTER' option in the top right of the screen in the plant survey mode when adding species.  Like this that already exists for the general survey mode
![ir app](https://user-images.githubusercontent.com/2699478/72788451-dac6aa80-3c29-11ea-8334-1dd412346380.png)

**Comment by kazlauskis** [comment]
Thanks, I will add the filter. It will allow to choose between different vascular plant groups that we allow for that survey and also common vs scientific name searches. 

As an idea, in the future, the filtering menu could also allow to choose from user defined lists.
