### ISSUE TITLE
Recording as undefined

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#18]
Is it worth allowing people to record something as "unidentified" in the species field, e.g. if they are outside, take a photo and want to record an accurate location, but can't identify it until they get home? At the moment a species name seems to be required before you can add other details to the record. If we do have "unidentifed" we'd also need to set it so that the record can't be finally submitted until a species name was added.

**Comment by johnvanbreda** [comment]
Yes, I think we need something like this, though I think there is no need to have a record with a fake "unidentified" species name as this is simply a record where you've not yet added the species name. At first I was really pleased to see that I could easily collect a set of photos which are geotagged and dated but without species names, then simply add species names later. However when I referred back to the photos I found I could not view the record or the photo without entering a species name first. If I could enter a record without species name (including probably a comment and photo) then later review that record to identify it and finally add the species name, it would be great from my perspective. 

I suppose there is a potential requirement to allow you to save unidentified records into iRecord but maybe that's actually better handled by posting to iSpot?

**Comment by kazlauskis** [comment]
The main reason why the app forces user to select a species before adding any data is because very soon we will have dynamic attributes. That is have different number ranges, stages etc. and possibly different attributes list per species group, making it difficult to transform already selected attribute values to the ones required by the species group.

Example: you have created a record with a photo, then changed the number to 2-5 and stage to 'Adult'. Then you select the species as '10 spot ladybird' and the ladybird survey requires different number ranges and also different species stages. This makes a conflict that is very hard to resolve automatically. I hope you see what I mean?

**Comment by johnvanbreda** [comment]
That makes perfect sense. But, the comment field is presumably something which could be always available, much like the photograph. Therefore you could still allow the other fields to be dynamically created later when the species is known.
Having an "unidentified" species rather than a blank species does not really fix anything, as when you select the species later the fields available will change.

**Comment by kazlauskis** [comment]
Oh yes, I agree that 'unidentified' does change anything, my initial comment was actually a users question that I have put down here for a discussion. 

I also think that the comment attribute should be available, I  just need to think of a way to make it accessible (maybe a swipe left would reveal a delete AND a comment button as well). 

Closing this now.
