### ISSUE TITLE
General/Moth/Plant Survey buttons only work if the centre is clicked

### ISSUE THREAD

**Issue by ColinHCampbell** [NERC-CEH/irecord-app#180]
Hi,

The General/Moth/Plant Survey buttons which you get when you long-hold the '+' button only work if you click the centre of the button.  I've been clicking on the edge (i.e. away from the text) and instead of loading the record/survey entry screen it just goes back to standard record list view.

The new surveys functionality is awesome by the way!

Col

**Comment by kazlauskis** [comment]
Well spotted, I will fix it 👍
