### ISSUE TITLE
Bug in bird dynamic attributes?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-app#187]
See iRecord forum post and example record:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=13149258
https://www.brc.ac.uk/irecord/node/7956

A bug? @kazlauskis

**Comment by kazlauskis** [comment]
Yes, this is a bug, for some reason, birds use butterfly number ranges. I will fix it asap.

**Comment by kazlauskis** [comment]
This is fixed now v5.1.2, I'll close it when app stores finish reviewing update.
