### ISSUE TITLE
Add an explicit recorder name attribute to all records captured via the app

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#189]
When using the app in standard single record mode, no recorder name is explicitly captured. Instead the recorder attribute is populated from the warehouse People table. This causes problems if a user changes their name. Even if the name is updated in the warehouse, it does not automatically get refreshed in the records, and the recorder is unable to manually edit the records because there is no recorder attribute available.

It's very hard to know whether we should automatically update recorder names on records when a user changes their name - some people will want all recors to have the new name, others will want to distinguish records added under their old name from records added under their new.

But if we can store the recorder name as a separate attribute it at least allows the recorder to manually edit their records if they wish.

**Comment by kazlauskis** [comment]
Thanks. Is there a need for app to support multiple recorders? Devices are more personal than web forms and I can make the app to auto-set the name of the logged in user, do we want the user to be able to edit this field to change or add more recorders?

**Comment by kitenetter** [comment]
I'm sure you're right that the app is generally for personal use, but I can also imagine situations where one person among a group of recorders takes responsibility for adding records to the app on behalf of a group. So I think it would be good if the recorder name was editable in single record mode in the same way as it is in survey mode.

**Comment by DavidRoy** [comment]
I agree.  Recording can be done in groups.  We already allow this via the plant-grid mode?

**Comment by kazlauskis** [comment]
OK, will add another field. Yes, we have `recorders` for other surveys in the app. I will explore the ways to organise the growing number of fields so that the casual recording survey has the most used attributes ready at hand but still allowed recording all the other information so to keep it simple and easy to use.
