### ISSUE TITLE
Name missing from app

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-app#191]
Chorerades Marginatus. Golden haired robber fly
Not found on the Android app but present when using the website
Thought you might need to know.
There seem to be quite a few discrepancies between the two

https://www.brc.ac.uk/irecord/node/8073#comment-5524

**Comment by kazlauskis** [comment]
I've updated the species dictionary in the app. Seems that both species are now consistent between the app and the website.
