### ISSUE TITLE
Encourage correct use of date for moth-trap records

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#193]
The convention for recording moths is that the data should be set to the date the trap was put out, i.e. in the evening. But data entry is often done the following morning, and in that case the app defaults to using the data of data entry, which is incorrect.

Options:
- Don't allow a default date, insist that the recorder picks the date themselves
- Allow a three-way choice: today/yesterday/pick a date

Also, add some explanatory text to the app date field to remind people what the convention is.

**Comment by kazlauskis** [comment]
The app won't prefill the date now and the user will have to manually enter it.
