### ISSUE TITLE
Additional dynamic attribute needed for Odonata

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#197]
Today BDS requested us to add an additional stage attribute to recording forms on the iRecord website - it would be good to replicate this on the app when we can. 

This new attribute is occAttr 842, "Sc" (= Oviposition scars), so the full list is now:
- Ad = Adult
- Co = Copulating pair
- Ov = Ovipositing female
- Sc = Oviposition scars (Willow Emerald only)
- La = Larva
- Ex = Exuvia
- Em = Emergent

The new attribute only applies to a single species, so could be set to only appear for that one species in the app, but there is no problem with it appearing for all Odonata (which is what happens on the website).

**Comment by kitenetter** [comment]
@kazlauskis it would be good if we can fix this next time the app is updated. Do you need any more information from me?

**Comment by kazlauskis** [comment]
Sure, I will add it in, I haven't had the time to update the UKSI list yet, so this will come together with that in the update. I will make it to appear to all Odonata for now.

**Comment by kitenetter** [comment]
All Odonata is fine, thanks.
