### ISSUE TITLE
Update app species dictionary to bring it in line with the UK Master List

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#198]
Following the update to the latest UKSI names in the warehouse on 3 August, species names in the app no longer align with the names on the website.

We need to schedule an update to the app, and to work out how best to deal with future updates. For the website we hope to move to a situation where there are more frequent batch updates, instead of the current occasional full replacement updates.

**Comment by kitenetter** [comment]
The iRecord version of the UKSI names is being updated again on Thursday, and it would be good to keep the app in line with that if we possibly can.

We've also had a specific request to remove the English name "Water beetle" from the app. The UKSI links "Water beetle" to the extremely rare "Ochthebius poweri" and this is causing problems for the recording scheme. I hope this name will be removed from UKSI as part of the update, but if it is possible to remove it from the app straight away that would be good.

**Comment by kazlauskis** [comment]
I could try to update the species list in the app sometime this Friday and then push it to the app stores, would that be OK?

**Comment by kitenetter** [comment]
That would be great, but maybe best to wait until the middle of next week just to ensure that there are no issues with Thursday's update?

**Comment by kazlauskis** [comment]
Sounds good, if I don't hear from you then I will update the list sometime next week then.

**Comment by kitenetter** [comment]
We've just had another report of a common problem whereby people using the app are getting mixed up between the Horse Chestnut moth and the Horse Chestnut tree. At the moment the app gives both of them the same English name:

![image](https://user-images.githubusercontent.com/16039111/106287516-c9ea4500-623e-11eb-9592-3047f491516c.png)

After the UKSI update I **_hope_** that you will find that the tree is called "Horse-chestnut" and the moth is called "Horse Chestnut Moth". If it possible to check that this does indeed happen that would be appreciated.

**Comment by kazlauskis** [comment]
Thanks for the screenshot. I will check it.

**Comment by kazlauskis** [comment]
<img width="286" alt="Screenshot 2021-02-06 at 09 29 34" src="https://user-images.githubusercontent.com/7383162/107114456-d6355a00-685d-11eb-8892-378d95e4d65a.png">
