### ISSUE TITLE
Aerial photos not displaying in iRecord app

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#200]
This was reported yesterday (14 Oct) - the aerial photos are not displaying in the app, so that when you zoom in to find a location you are shown a blank screen. Also affecting the Wales LERC app.
@kazlauskis

**Comment by kazlauskis** [comment]
Thanks, one of the mapping services providers have changed their API and this requires updating any apps that use it. We will fix it with the next app release.

**Comment by kitenetter** [comment]
Thanks @kazlauskis Do we know when the next release will be? The Welsh LERCs are hoping this can be fixed soon, and it does make it difficult to add record locations for people using the maps on both apps.

**Comment by kazlauskis** [comment]
Yeah, I've spoken with them. I am plowing through some other work now so I think the earliest we could have the update is sometime next month. I hope that's OK!

**Comment by kitenetter** [comment]
It looks like Open Street Map is also missing, presumably that is a similar issue.

**Comment by kazlauskis** [comment]
Yes, that's the same mapping provider. Only the ordnance survey maps will work now.

**Comment by kitenetter** [comment]
Here's the workaround that I have tweeted and will add to the iRecord forum.

![image](https://user-images.githubusercontent.com/16039111/96241827-98ed4980-0f9a-11eb-9ae7-873cd9014c09.png)

**Comment by kazlauskis** [comment]
Ah, nice! Thanks for finding it.

**Comment by kitenetter** [comment]
@kazlauskis can you let me know when the update is due to be issued, and the maps become available to users again, so that we can announce it.

**Comment by kazlauskis** [comment]
It is fixed and available to the public now. The latest version is 5.1.4. Here is the changelog:
```
Fixed Satellite map layer display
Fixed Plant Survey vice county setting
Fixed General and Plant Survey date settings
Fixed multiple recorder name upload for General Survey
```
