### ISSUE TITLE
Provide guidance on date selection for moth survey users

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#202]
Feature request:
When trapping moths overnight, the convention is that the date recorded should always be the date that the trap was put out, not the date that the trap was opened and checked. That is, it should be the date of the evening when trapping started, not the morning when trapping finished.

Users can specify whichever date they want in the app, but it defaults to today's date. This has led to users entering data with the wrong date if they are checking their traps in the morning and fail to reset the default date to the day before.

It would be helpful if we could add a 'help' message somewhere to remind users of the convention, e.g. so that if they are using the moth survey part of the app, when they go to the date there is a reminder;
"If trapping overnight please enter the date for the evening on which the trap was put out"

**Comment by kazlauskis** [comment]
Thanks, I have added this ticket to the next release tasks. Feel free to tag this way any other work that you would like us doing for the next app version - select `milestone`.

**Comment by kitenetter** [comment]
@kazlauskis I don't think I have permission to add tags or milestones in this repository

**Comment by kazlauskis** [comment]
Oooh, let's fix that 😄 I have now sent you an invitation to join the repo.
