### ISSUE TITLE
Selecting a species from the list does not close species list on iPad

### ISSUE THREAD

**Issue by rich-frost** [NERC-CEH/irecord-app#204]
Using the latest iRecord app (5.2) on an iPad; if you select a species from the list it does not close the list. You can click multiple times and nothing happens - when you go back however you have multiple pending surveys.

Seems like a click/touch handler isn't working quite right for iPads.

**Comment by kazlauskis** [comment]
Thanks for reporting this, we'll have a look at it.

**Comment by DavidRoy** [comment]
I have the same problem on my iphone.  If I select a species it adds a record but does not leave the species select page. This can result in multiple records
