### ISSUE TITLE
Enter location with a grid ref

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#207]
I'm trying to use the moth survey part of the app, and I want to type in my grid reference so that it is consistent with all my other records for the same location. However, it seems to be impossible to type in a grid reference - as soon as I try to do so the app converts the partial grid ref into an incorrect lat/long coordinate.

Is the app intended to allow grid refs to be entered (in which case it isn't working properly), or is that not currently possible (in which case I'd like to request it as a new feature)?

**Comment by kazlauskis** [comment]
It should be working. Do you have 'Use Grid Ref' turned on in the Settings?

**Comment by kitenetter** [comment]
No I didn't! Apologies for not checking! It's fine with that setting (maybe it got changed during an update?). Closing.
