### ISSUE TITLE
Unexpected prompt for "eBMS account" on a new install of iRecord App

### ISSUE THREAD

**Issue by DavidHepper** [NERC-CEH/irecord-app#209]
I recently changed my mobile and downloaded the iRecord App v5.2. On sign-in today the app has an identity crisis: the banner asks for an eBMS account, rather than an iRecord account. However, I successfully logged in with my iR username and password.
![P1050386](https://user-images.githubusercontent.com/24915271/112669651-e0d0a080-8e57-11eb-8eba-55841b93be25.JPG)

**Comment by kazlauskis** [comment]
Oh, no! I have fixed this now in the code and this will be pushed out with the next app release. Thank you so much for raising the ticket here.

**Comment by DavidHepper** [comment]
Impressive response! Thanks, K.
