### ISSUE TITLE
Request for additional guidance to be added to the "moth survey"

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#210]
Butterfly Conservation have asked if we can add guidance to the app moth survey to match that given on the [moth recording form](https://www.brc.ac.uk/irecord/enter-moth-sightings) on the iRecord website.

The wording requested is:
"For trapping records, please enter the date the trap was set (turned on), **not** the date for the following morning (if the trap was run overnight).
"If you are recording larvae, cases or leaf-mines please add the foodplant in to the comments field, as this is often needed to verify the records.
"For the quantity, **do not** enter a zero to mean "present but not counted" - if the quantity was not counted, leave this column blank (if you use a zero iRecord will interpret that as meaning the moth was absent)."

**Comment by kitenetter** [comment]
See also #193

**Comment by kazlauskis** [comment]
Abundance can't be set to 0 or removed in the app so the last point doesn't apply. I have added the stage and date messages to the relevant app pages.

<img width="338" alt="Screenshot 2021-05-28 at 19 10 59" src="https://user-images.githubusercontent.com/7383162/120025350-73242a80-bfe8-11eb-9b2b-13f06be355f4.png">
<img width="337" alt="Screenshot 2021-05-28 at 19 10 39" src="https://user-images.githubusercontent.com/7383162/120025363-78817500-bfe8-11eb-829e-84f82ee65771.png">
