### ISSUE TITLE
Recorder name formatting issue

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#215]
A regular app user has queried why their name varies between "Surname, Forename" and "Forename Surname" when using the app. This appears to be the result of adding some records as individual records, and some via the Plant Survey option.

Does the recorder name get treated differently if using the survey option?

Can we standardise it so that it is always "Forename Surname"?

**Comment by kazlauskis** [comment]
It is correct in the app. In the plant survey and others we use "Forename Surname". The individual record survey doesn't capture the 'recorders' field in the app, so I think the "Surname, Forename" instances should originate from somewhere else then (website?).
