### ISSUE TITLE
Move "upload all pending" button to home page

### ISSUE THREAD

**Issue by cubitmg** [NERC-CEH/irecord-app#216]
As a recorder when I have multiple records ready for upload then I would like an Upload All Pending button on the Home screen so that rather going into each one and touching Upload I can do so more efficiently.

**Comment by kazlauskis** [comment]
@cubitmg there is an option in the app Settings at the moment.

**Comment by cubitmg** [comment]
Hmmn :-)

Great that the logic is there, but should it really be in "Settings"?

I can see that adding a new icon for 'Upload All' to the Home screen would be difficult, but this raises a bigger topic and that is the whole navigation from that home screen which seems like something that would pay to have some fresh thinking about? 

I can put some more thought into this and raise a new ticket, but initial observations are:
- The home screen of this and the Butterflies app seems to be fundamentally designed around a casual sighting with a + or Record icon bottom centre. When Group records or starting from a Photo have been added to the app these seem to have caused some design issues and each are invoked using a different mechanism (neither of which are very intuitive in my view).
- Maybe the home screen should be more of a Record entry style menu and have a separate 'My records' screen as the Butterflies App does. The Home screen menu could have clearer buttons/icons for Add Casual Record, Add Record from Photo, Add Activity List, Add Group Survey. 
- The latter two above could allow selection of the activity or group as a next step or this could be set in settings (short press) or long press to allow the selection?
- Activities icon could be removed from the icons at the bottom and could be under Settings or its own item under Menu.
- On a slightly different topic, having to use the "<- Back" option at the top of the screen is not consistent with almost all Android apps that expect Android's 'Back' button to be used.
