### ISSUE TITLE
Upload failure notification reason.

### ISSUE THREAD

**Issue by cubitmg** [NERC-CEH/irecord-app#217]
As a recorder when uploading from the Moth Survey type I would like to have a notification warning to tell me why the Upload isn't happening when an error such as 'no method' is causing a failure or a warning icon on the offending field.

**Comment by kazlauskis** [comment]
I agree this should be improved. Do you know which fields are causing errors?

**Comment by cubitmg** [comment]
The one that caught me out earlier today was Method in the Moth Survey.
I have just tried it again and entered nothing and tried to upload. A message was returned in this case and said "Some values incorrect or missing - sample: location, date. So, some checking logic is being run, but may not be survey specific? (The location warning only occurs if the GPS has not returned before trying to Upload.)
The location field contains both grid ref and name text. The "Name missing" in red is maybe a UX design approach that could be followed for consistency (as well as the error message)?

**Comment by kazlauskis** [comment]
Thanks, that's very useful. The app should not fail to upload silently and should inform the user.
