### ISSUE TITLE
OS OpenSpace API being withdrawn in August

### ISSUE THREAD

**Issue by JimBacon** [NERC-CEH/irecord-app#219]
Refer to https://www.ordnancesurvey.co.uk/business-government/tools-support/openspace-support

**Comment by kazlauskis** [comment]
@JimBacon nice to see you back! Thanks for the ticket, I didn't know they're stopping the service.

**Comment by JimBacon** [comment]
Thanks! iRecord website has been hit already because we use a different API. The lights went out for us at the end of last week. We are reviewing the terms and conditions for the replacement service at the moment.

**Comment by JimBacon** [comment]
For examples of how to implement, see
- https://github.com/rob-murray/os-leaflet/issues/29#issuecomment-653727586
- https://labs.os.uk/public/os-data-hub-examples/os-maps-api/zxy-27700-basic-map
- https://labs.os.uk/public/os-data-hub-examples/os-maps-api/wmts-27700-basic-map

**Comment by johnvanbreda** [comment]
Given the above examples, it would be nice to integrate the new API in our Leaflet/Elasticsearch output component.

**Comment by kazlauskis** [comment]
The update is coming out now as v5.4.1
