### ISSUE TITLE
How do I clear an abundance value to zero or blank?

### ISSUE THREAD

**Issue by DavidHepper** [NERC-CEH/irecord-app#224]
When a dragonfly taxon is selected in the App, the life-stage abundance fields are shown. If I select a value, e.g. for Emergents (Em), but then change my mind and wish to record only Adults (Ad) it seems impossible to clear the value selected for Em. Can there be a 0 or blank option in the picklist, please? Have I missed another way to clear a field that has been set?

**Comment by kazlauskis** [comment]
Thanks, we'll fix this.

**Comment by kazlauskis** [comment]
That's done now.
