### ISSUE TITLE
iRecord app web page editing

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#225]
Who has editing control over this web page:
https://irecord.org.uk/app/

It's a minor issue, but the images on the page always seem to load very slowly, and it would be good to reduce their size. Happy to do that if someone can give me editing permission.

Do you have access to this page @BirenRathod ?

**Comment by BirenRathod** [comment]
@kitenetter It is down to me, so send me the image or I can reduce the size. it is not dynamic or content management website, so I have to do manually. So nothing to do with permission bit.

**Comment by kitenetter** [comment]
@BirenRathod I assume it is just the size of the images that is slowing things down, so if you can just reduce the file sizes that would be great, but let me know if you want me to edit the images and send them to you.

**Comment by BirenRathod** [comment]
@kitenetter all images I assume? Also, any recommended size? They are all above 1200px width, so should be lower then that.

**Comment by kitenetter** [comment]
300px width seems fine - here are some re-sized versions:

[app images.zip](https://github.com/NERC-CEH/irecord-app/files/6945243/app.images.zip)

**Comment by BirenRathod** [comment]
@kitenetter Thanks for images. I have copied them onto live now.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 

That seems a lot better, but there are still two issues.

One is that the phone screenshot image in the green strip at the top still seems to be quite large - I'm not sure how that image is controlled.

And the other is that I hadn't realised that the images further down the page were part of a carousel, so it looks like not all of them have been resized.

Is it possible to ensure that all images on this page are the same 300px width?

**Comment by BirenRathod** [comment]
@kitenetter

Also, top image has very large pixel too and it is also possible to update. here is the link to download -> https://irecord.org.uk/app/index_files/screenshot-1.png
and this too
https://irecord.org.uk/app/index_files/screenshot-6.png

 they all 300px, did you clear the cache of the browser?

**Comment by kitenetter** [comment]
I thought I had cleared it but not certain. In any case the page is loading much better than it was before, thanks.

Closing.

**Comment by BirenRathod** [comment]
@kitenetter Yes, it loads much better way then before. Also, you can check all file size through Chrome or Firefox. Again you need to clear the cookies.
