### ISSUE TITLE
LERC Wales app allowing records to be submitted by users who are not logged in

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#226]
Not sure if this is the best place to report this issue. It seems to be similar to the issue recently discussed for the Bloomin Algae app.

Some LERC Wales app users are submitting records without logging in, which presumably means they have not verified their accounts. This results in records that have no recorder name, and has been queried by a verifier.

**Comment by kitenetter** [comment]
Also, the verifier wishes to edit the recorder name for these records, which doesn't appear to be possible within iRecord. We may need to run a database update to achieve this once the issue is fixed.

**Comment by kazlauskis** [comment]
This is fixed for the iRecord App now and will be moved to the LERC app with the next update.
