### ISSUE TITLE
Old iRecord Dragonflies app still being offered

### ISSUE THREAD

**Issue by DavidHepper** [NERC-CEH/irecord-app#227]
Hello @kazlauskis, please would you unpublish / delete / nuke the old app from https://chrome.google.com/webstore/detail/irecord-dragonflies/ajiopnflbgclbhnjhmepnkhmcacdkmap and anywhere else. Biren can't. We're very happy with the generic iRecord app.

**Comment by kazlauskis** [comment]
Sorry, this isn't something I can do without the right credentials and I am not sure what is the owner's account for this store. UKCEH should have any login details that I have left them and so you should ask someone else at UKCEH to have a look at it.

It would be better to move this ticket to the iRecord website issue tracker where more people might be able to help you out: https://github.com/BiologicalRecordsCentre/iRecord/issues

**Comment by DavidHepper** [comment]
It started on there... >https://github.com/BiologicalRecordsCentre/iRecord/issues/1133
