### ISSUE TITLE
Feature request: Scientific name on Pending screen

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [NERC-CEH/irecord-app#229]
SWSEIC
Scientific name on Pending screen
I feel it would be useful to view the scientific name on the Pending/Uploaded screen for each record. A good example of why this is important is if you enter 'Frog' you are recording the genus Rana, and not the species Rana temporaria. As a verifier I get many records which are incorrectly assigned to the genus and not the species, and that is partly a functio of the data entry not being particularly clear. I know this is also a result of the how the name occur in the species dictionary, but having the scientific name displayed (like the taxonomic group is displayed on the drop down list) would be helpful to users in spotting potential errors. You could also argue that the taxonomic group should also be shown to avoid similar confusion (Painted-lady plant vs Painted Lady butterfly). Has this been considered?

Mark

**Comment by kitenetter** [comment]
I think this will be covered by #183 - closing
