### ISSUE TITLE
Can it be made easier for an App user to submit records when back home?

### ISSUE THREAD

**Issue by DavidHepper** [NERC-CEH/irecord-app#231]
iRecord ID 22902933 contains the following complaint by the original recorder about using the iRecord App:

> The problem that I have with this App is that if you look at where i saw the insect, it was at WWT Slimbridge, but due to deficiencies in the way the App 'works' it logs it at Bibury Road. My method of recording is to log what i see when I'm out-and-about and then list it all at the end of the day or the next day. i am aware that the map references do not match up with the site where the sightings are observed, but I put that down to the App. i do not have time to keep on correcting the site name to match the map references. Maybe it's something that needs addressing sooner rather than later. The eBird App is much simpler and quicker to fill in, as is the iNaturalist, which i was going to default to when your app was not responding. If you want me to continue sending in my recordings then it might be better to address the deficiencies in the system before i get fed-up.

Should we simply advise him to use the app in real time, recording as he goes around the site? In bright sun this is hard to recommend, given the current poor screen technology of mobiles for handling incident light, as opposed to backlight.

**Comment by kazlauskis** [comment]
@DavidHepper I understand the user is using the General Survey and entering the species list at home instead of real-time. In that case the person can toggle off the automatic GPS for the list entries. All the species entries would then default to the survey site location instead of capturing precise occurrence locations. 

The setting can be found under the general app **Settings** named **Geolocate Survey Entries**.

**Comment by DavidHepper** [comment]
Thanks. Does it matter which Survey is used? I'm guessing not.

**Comment by kazlauskis** [comment]
You're right, it doesn't matter. The only two surveys that allow to capture species lists with the precise locations is the Plant and General surveys. This setting will disable the GPS for both of these.
