### ISSUE TITLE
Change the Ordnance Survey key from the UKCEH account to the NERC account.

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#233]

**Comment by kazlauskis** [comment]
@JimBacon this comes from our email discussion on 27 April this year. Can you please send me the new OS maps key for the iRecord App?

@DavidRoy I'd like to include OS maps to other iRecord-branded apps like the iRecord Butterflies and the iRecord Grasshoppers. Would that be OK?

**Comment by DavidRoy** [comment]
@kazlauskis - we can use this across the 'BRC' apps as they receive NERC funding

**Comment by JimBacon** [comment]
Blocked on this at the moment until an administrator accepts some new terms and conditions. I have emailed a contact at NERC for assistance.

**Comment by JimBacon** [comment]
New key sent by email.
