### ISSUE TITLE
npm install fails due to unpublished dependency

### ISSUE THREAD

**Issue by raffael-mnhn** [NERC-CEH/irecord-app#235]
**Describe the issue**
npm install fails due to unpublished dependency

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bit%2fflumens.apps.utils.analytics - Not found
npm ERR! 404 
npm ERR! 404  '@bit/flumens.apps.utils.analytics@0.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'irecord-app'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**To Reproduce**
1. clone repo
2. cd into directors
3. npm install

**Expected behavior**
npm install should just finish without error.

**Comment by johnvanbreda** [comment]
I had to run the following
```bash
$ npm config set @bit:registry https://node.bit.dev/
```

Contact me if you want me to send my rough notes on getting a dev environment working in Windows. Also - there is an MNHNL version at https://github.com/MnhnL/irecord-app - I'll let you know when I've pushed my code.
