### ISSUE TITLE
Add automatic species identification from photos

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#238]
To add image classification for photos attached to records. A user would attach a photo to a record, and the app would automatically send the pic for identification to our Drupal proxy in the background. If the classifier has results, then these suggestions would be shown to the user on the species search page and when opening the photo from the records' gallery. This is similar to how we have done it in the iRecord Butterflies app.

This would require the iRecord website to proxy app photo ID requests to one of the matching classifiers (PlantNet - plants, Waarneming - for everything else). 

The proxy wouldn't know beforehand which species group the photo is coming from. One solution would be to ID it first with a generic classifier like Waarneming and then re-classify with a species-specific one, i.e if the top result is a plant, then send the pic to the PlantNet to improve the accuracy of the results.

1. Take a photo:
![Screenshot 2022-09-19 at 11 36 34](https://user-images.githubusercontent.com/7383162/190979811-a6a3bad3-9943-47f4-9fff-f0af4c254fbc.png)

2. The pic is being identified:
![Screenshot 2022-09-19 at 11 36 59](https://user-images.githubusercontent.com/7383162/190979821-f9ab7235-4619-404a-8d49-6034f6a55bbe.png)
![Screenshot 2022-09-19 at 11 37 22](https://user-images.githubusercontent.com/7383162/190979823-78b04c11-1abb-492f-9d21-3957e38877fd.png)

3. Suggestions:
![Screenshot 2022-09-19 at 11 45 14](https://user-images.githubusercontent.com/7383162/190981036-c6e0cd4e-ae09-45a1-be54-4703f7f14a0b.png)

**Comment by kazlauskis** [comment]
@JimBacon this would require some of your help. Do you have any thoughts about this? 

The iRecord site currently has your proxy module installed and configured to accept only requests for moths and butterflies. We will want to accept other species groups now too. So one way would be to open the current proxy for other apps and species groups - possibly reducing the accuracy of the results for the eBMS and iRecord Butterflies apps. Another option would be to duplicate the proxy module and keep it parallel to the existing one.

**Comment by DavidRoy** [comment]
@JimBacon we would also want flexibility in which classify to use.  Plant net for plants and NIA for everything else

**Comment by JimBacon** [comment]
My thought is that proxy should accept a species group parameter with the photo to inform the choice of classifier and how it filters results. If the parameter is absent then it proceeds as you suggest. This would ensure no loss of accuracy for eBMS and iRecord Butterflies if they send that parameter. It would also improve the performance of the iRecord app if the recorder was able to pick the species group. It would then only need one instance of the proxy to install and maintain on the Drupal site.

**Comment by kazlauskis** [comment]
I like the parameter idea.

**Comment by JimBacon** [comment]
I've been looking at the way the proxy works currently. It is built as a plugin for the standard [API Proxy](https://www.drupal.org/project/api_proxy) module. Using this we can easily provide a proxy for each additional classifier.

The logic that decides which classifier to call and whether to call additional classifiers to refine results could be built in to the app or in to an additional Drupal module. If each app were going to do something different then I'd probably build it in to the app. If they all were going to work the same then doing it once in Drupal would seem better.

**Comment by kazlauskis** [comment]
Thanks, I don't mind calling different proxies for different species groups from an app but I suggest centralising the logic at the website level. This would reduce mobile data usage, use the cloud to do the heavy lifting and, at this point, I don't see why apps would use it differently. Ideally, the app would treat the Proxy as a black box, providing a pic(s), optionally a species group and/or coordinates. Any post-processing of classifiers' results would be at the website, returning a clean species list back to the app. 

There could be multiple proxies in the website linked to different classifiers and, as you say, we can have another module on the top that is responsible for the refinement of the results. This module could first call a generic classifier proxy and if the top species is of a certain group then re-classify it with a species-group specific proxy. 

Sometimes a suggestion pops up to filter species lists based on the current user location. So like modular building blocks we could add another module to accept coords and refine the results further. This is for the future though!

Whichever approach we take, classifiers have differently formatted outputs so, at the very least, I'd like the Proxy to abstract that to a single format that apps can ingest.

**Comment by DavidRoy** [comment]
I agree. It makes sense to do this at the website end.  Given current requirements, the apps would all work in the same way

**Comment by kazlauskis** [comment]
@JimBacon do you know roughly when you could start the work on this?

**Comment by kazlauskis** [comment]
That would be great! I am working on the iRecord App right now and could integrate this as soon as it is ready.

**Comment by JimBacon** [comment]
@DavidRoy are you happy with the PlantNet terms and conditions:

> Any free use of Pl@ntNet API might acknowledge Pl@ntNet with the following sentence : "The image-based plant species identification service used, is based on the Pl@ntNet recognition API, regularly updated and accessible through the site https://my.plantnet.org/", and the logo : 


![image](https://user-images.githubusercontent.com/2545390/196983533-2d1bdf51-2112-4621-9c08-afc8a7c50170.png)
![image](https://user-images.githubusercontent.com/2545390/196983614-89f31e04-d647-47a9-a807-462187d042ee.png)

The use of the word 'might' could be a mistranslation. In response to my contacting them, they specifically say we would need to add the logo.

**Comment by DavidRoy** [comment]
yes, these T&Cs are very reasonable.  We should also acknowledge the NIA classifier
@AugustT has good links to PlantNet

**Comment by JimBacon** [comment]
Hi @kazlauskis, I've added an argument to the POST data to override the species groups that the image classifier results will be limited to. I've documented it at https://github.com/Indicia-Team/drupal-module-api-proxy-waarneming.

E.g. If you include `groups[] = 0` in the POST data then it will remove all restrictions allowing you to try to identify anything.

It is backwards compatible so, without the argument, it will continue to function as before. It is deployed to iRecord.

This is just the first step. When Tom is back and we can sort out our accounts with PlantNet, I'll move on to that.

**Comment by kazlauskis** [comment]
Excellent! Have you thought of how best to combine the AIs? If the output of the waarneming proxy is going to be standard across all the proxies/AIs then I could start the integration to the app.

**Comment by JimBacon** [comment]
No. Until I have a PlantNet account and can start experimenting with the API, I'm not making any assumptions.

**Comment by DavidRoy** [comment]
The general idea is that we use PlantNet for plant images and NIA for the rest.  There maybe other classifiers we want to use in future. I guess there will need to be decisions at the app/survey level about which classifier(s) to use, or defaults set at the module end.

The update to the module by Jim to allow a taxon_group parameter will help, but does the module also need a parameter for 'classifier' so the apps can choose which one to use, e.g. ESurveyor uses Plantnet

**Comment by JimBacon** [comment]
There will be a module for each classifier and one module to rule them all (or rather to provide a uniform interface where that is what we want)

**Comment by JimBacon** [comment]
@kazlauskis, what is the minimum information you need in the response from the classifier?
The simpler it is, the more chance we will have of coercing all the different classifiers in to one form.

**Comment by kazlauskis** [comment]
@JimBacon For each species suggestion it would be good to have this info:

```json5
{
    "classifier_id": 20098, // 20098 – Waarneming, 20099 – PlantNet... from: http://warehouse1.indicia.org.uk/index.php/termlist/edit/995?tab=terms
    "classifier_version": 'v1.0.0', // can be null if classifier version isn't known

    "probability": 0.99,
    "taxon": "Lysandra bellargus", // ideally, this would be the preferred one, if not then "preferred_taxon" should be added
    "taxa_taxon_list_id": "240856", // same as above, adding "preferred_taxa_taxon_list_id" if not preferred
    "group": 123 // this could be optional but we already use this in the iRecord Butterflies app and it would be useful to have in other contexts
}
```

Alternatively, the `classifier_id` and `classifier_version` values can be pulled up into a higher scope:
```json5
{
    "classifier_id": 20098, // 20098 – Waarneming, 20099 – PlantNet... from: http://warehouse1.indicia.org.uk/index.php/termlist/edit/995?tab=terms
    "classifier_version": 'v1.0.0', // can be null if classifier version isn't known

    "suggestions": [
      {
         "probability": 0.99,
         "taxon": "Lysandra bellargus", // ideally, this would be the preferred one, if not then "preferred_taxon" should be added
         "taxa_taxon_list_id": "240856", // same as above, adding "preferred_taxa_taxon_list_id" if not preferred
         "group": 123 // this could be optional but we already use this in the iRecord Butterflies app and it would be useful to have in other contexts
      }
    ]
}

```

**Comment by JimBacon** [comment]
That looks good.
`group` I would make `taxon_group_id`, from the Indicia species list, rather than from the classifier.

Jim.

**Comment by JimBacon** [comment]
Hi @kazlauskis 

I've done a first draft implementation, still without anything related to plantnet, of how I envisage this working.
There is a new repo, https://github.com/Indicia-Team/drupal-8-modules-indicia-ai.
The readme file at https://github.com/Indicia-Team/drupal-8-modules-indicia-ai/tree/master/indicia_ai should tell you what you need to know to try it.
Currently it is on a branch of the irecord website, accessible at https://ai-brc-irecord.pantheonsite.io/
There maybe some CORS configuration needed in the modules for the app to work but it is working for me from Postman.
![image](https://user-images.githubusercontent.com/2545390/199210958-9ef3f3f6-67d8-4abf-a76d-5dbb8505a40f.png)

**Comment by kazlauskis** [comment]
@JimBacon thanks, I've played around with it, and it works fine on my end too. I had to add an extra CORS config line in the settings, but that's about it. I am happy with this interface, is there anything else you want to do before releasing this to live iRecord?

**Comment by kitenetter** [comment]
@kazlauskis @DavidRoy I haven't been keeping up with exactly what the scope of this is, and what users and verifiers will see. Do we need to do any comms or guidance before making this live? Will it only affect records from the main iRecord app? Has the image recognition gone live on the butterflies app yet?

**Comment by DavidRoy** [comment]
@kitenetter this step is about the API module going 'live' on iRecord. The next step is then how we implement image classification in the irecord website and app

**Comment by kitenetter** [comment]
Thanks @DavidRoy - I'll stop panicking!

I'm still not seeing the 'suggestion' in my butterflies app - should I be?

**Comment by DavidRoy** [comment]
@kitenetter you should see this in the iRecord Butterflies app.  Were you one of the testers (i.e. the app icon has a yellow dot by it)?  You may need to install the live version from the app store.  v2.5.0 (225) is the live version

**Comment by JimBacon** [comment]
> @JimBacon thanks, I've played around with it, and it works fine on my end too. I had to add an extra CORS config line in the settings, but that's about it. I am happy with this interface, is there anything else you want to do before releasing this to live iRecord?

Well it still needs work to create the module for PlantNet and to add the logic to pick which classifier to use.  Also the code is a bit clunky as the API Proxy is no longer quite such a good fit for what we are doing and it is all a bit fresh and untested. Some sort of error reporting in the response might be an asset. However, if it helps to keep the app progressing, we could release this and enhance it at a later date.

**Comment by kazlauskis** [comment]
I am going on leave until the next week so no rush but it would be good to have this module available when I'm back. If the interface won't change then the app can integrate with what you have already built and you can progress with the plantnet work independently. I imagine this area will only grow so more niche AIs will be added in the future. As long as the module's interface remains the same then the apps don't need to know what is being used behind the scenes.

**Comment by kazlauskis** [comment]
@JimBacon we are working on the iRecord App v6 release and it has enough new features added that I can push it out for Beta testing now. If you can finish the AI sometime this week, then I could bundle it with the current release or add the classifier to the app as v6.1 later if you prefer more time to work on it. What do you think?

**Comment by JimBacon** [comment]
@kazlauskis I can't do any development work for the next couple of weeks but I have deployed the initial version to live. I can't see the interface needing to change any time soon and changes could probably be backwards compatible anyway (e.g. adding extra fields to the response). Go ahead and incorporate it and we'll see if it stands up to the Beta testing.
