### ISSUE TITLE
Option to display AI classifier results as scientific_name in suggestion field

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [NERC-CEH/irecord-app#243]
From v6 Feedback 

"Not sure about use of insect English names, e.g. for bees – ideally want scientific as well, at least on the species name list when changing the identification name. It makes the image recognition unusable for people like me who don’t know the English names, and even for beginners it’s not always easy to know exactly which species an English name refers to, since they are not well-established for some insect groups (e.g. bees)."

**Comment by kazlauskis** [comment]
This will be fixed with https://github.com/NERC-CEH/irecord-app/issues/183
