### ISSUE TITLE
Make the grid-square alert available to all surveys

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#246]
At the moment, the grid-square alert is only available to the plant survey but it could be useful for general recording too. From the [irecord forum](https://irecord.org.uk/forum/mobile-applications/plant-survey-grid-square-alert):

> I use the app to record butterflies not plants so wasn't looking within the plant survey area.
I was thinking the grid square alert would  be operational as a general app feature, not just when a plant survey is active.

> The examle use-case would be when on a walk, getting an alert (ideally a vibration) when walking into a new tetrad (or monad, etc.) so you know it's 'more' important to start recording common species again given being in a new square.

> Ideally I'd record all butterfly sightings species all the time, but for common ones it's not feasible when say walking with other people to record every single sighting. So, getting a vibration from the phone would alert me that I'm in a new 'square' and the next few sightings are 'more' valuable.

> So, could this feature be moved up to a general function please? Even better would be to also provide it within the iRecord butterflies app which I use at the moment. This feature is important enough I'd switch back to the general app for longer walks and hikes if it wasn't added to the butterfly app.

**Comment by Sam-Amy** [comment]
Just to note this has been requested again, specifically with reference to the Species List.

**Comment by kazlauskis** [comment]
I am considering removing the new grid alert button from the Plant survey and adding an automatic alert toggle to the app settings. This toggle (default turned off) would allow the users who start a Plant or a Species List survey to receive new grid square alerts until the survey is finished. The new grid alert service would begin when a new survey is started and end when the survey Finish button is pressed. Unlike the current per-survey toggle, this app setting would persist between app sessions. For users interested in grid recording, they would turn this app setting on and, while surveying, would receive grid notifications. For those who aren't interested in this functionality, they would see a cleaner survey interface. This changes the functionality from a utility to a more integrated recording flow. What do you think?

**Comment by Sam-Amy** [comment]
Sounds like a great feature @kazlauskis
