### ISSUE TITLE
Question re image recognition and app surveys

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#249]
It appears that image recognition is available for individual records and for Species List Surveys, but not for plant and moth surveys. Is that correct, and are there plans to extend it to those other surveys?

**Comment by kazlauskis** [comment]
Yes, that's right. There is [a plan](https://github.com/NERC-CEH/irecord-app/issues/239) to enhance the two surveys that use the AI already with a plant classifier, but I don't know of any plans to add this functionality to the Plant or Moth surveys yet.

**Comment by kitenetter** [comment]
@kazlauskis does that mean that we are currently using NIA for all taxon groups, and that PlantNet has not yet been implemented in the app?

**Comment by kitenetter** [comment]
Thanks, hadn't realised that. Closing.
