### ISSUE TITLE
Improve OS maps

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#250]
We have migrated iRecord App Mapbox satellite maps from raster tiles to their vector + areal imagery alternative, which is cheaper and looks more modern. In the same way, we can upgrade the current OS map layer from raster 25k (explorer style) maps to their vector maps. This will allow us to remove some complex custom code that only serves the OS maps and will simplify the overall tech stack considerably. 

@DavidRoy @JimBacon Are you OK if we migrate the app OS map layer from raster to their vector alternative? There are some tradeoffs, like raster maps are more geared towards outdoor navigation and have clearer symbols for car parks, campsites etc. Where the vector maps allow you to zoom in more than 1:25k scale and, in theory, require less data bandwidth.

**Current OS map vector style (interactive [here](https://labs.os.uk/public/os-data-hub-examples/os-vector-tile-api/vts-example-custom-style#maplibre-gl-js)):**

![Screenshot 2023-04-20 at 12 26 52](https://user-images.githubusercontent.com/7383162/233323019-e56d94f3-9fe6-4db4-ac2f-41090ebd2a58.png)

**OS map raster style:**

![Screenshot 2023-04-20 at 11 13 22](https://user-images.githubusercontent.com/7383162/233322780-29beb677-0fe7-4cb7-94db-251de84b931c.png)

More vector styles here: https://github.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/tree/main

**Comment by DavidRoy** [comment]
@kitenetter @sacrevert what do you think?  The requirement is mainly for the non-built environment for OS layers?

**Comment by kitenetter** [comment]
Biggest drawback for me is the loss of meaningful information about footpaths and other rights of way.

**Comment by sacrevert** [comment]
I think that most outdoorsy folk will strongly prefer the 25k raster because the vector layer lacks a lot of information that is essential for navigation (especially the contours, but also a whole load of other symbology).

**Comment by kazlauskis** [comment]
Thanks, it sounds like you want to stick to the OS raster maps, I very much like them too. Here is another nice demo of the layer differences - zoom in to see the transition:
https://labs.os.uk/public/os-data-hub-examples/dist/os-maps-api/leaflet-zxy-example-additional-zoom-levels.php?auth=

We're moving towards vector maps in all other, not UK-specific projects. The new tooling and functions (e.g. offline maps, custom shapes) we are building might also benefit the iRecord App in the future, so I'll leave this ticket open for now. I also hope the OS will bring in their Explorer map symbology to the vector maps at some point.
