### ISSUE TITLE
Records submitted by users who aren't logged in

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#252]
I've just received two bee-fly records via the iRecord app from two different users, neither of whom was logged in (and thus there is no email linked to the records). I didn't think that was possible under normal circumstances?

**Comment by kitenetter** [comment]
There are two or three records from a non-logged-user that have ended with recorder name "Paul_Cook_5". That seems an odd name for someone to use, and if I look in the warehouse user table we have "Paul_Cook_1" through to "Paul_Cook_4" but no Paul_Cook_5. Is there something odd going on here?

**Comment by kitenetter** [comment]
Finding quite a few more, including at least one from the LERC Wales app. All have recorder names with underscores, suggesting warehouse user names, but with no such name in the warehouse. Some example record IDs:
10904442 (LERC Wales)
29894068
30117297
30040464
21211650
9970362

That last one is an example of a record that says it was added in 2019, but it definitely wasn't on my verification page yesterday and has appeared today.

This all seems very odd.

**Comment by kazlauskis** [comment]
Thanks! I'll check this asap.
