### ISSUE TITLE
Log in problem - Request failed with status code 500 

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#253]
Cannot log into the app with error message "Request failed with status code 500 "

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Login'
2. Enter correct email and password
3. Error message appears and then disappears leaving you stuck on the login page

**Expected behaviour**
Expected to log in

**Screenshots**
![status code 500 error](https://github.com/NERC-CEH/irecord-app/assets/104146164/6a484d32-4c6a-4327-9d5c-b7eab4139c5e)

**Smartphone (please complete the following information):**
 - Device: [|Samsung S21]
 - OS: [e.g. Android 12, UI 4.1]
 - App Version [6.0.5 (122)].
 
**Additional context**
This has also been reported by a few other users.

**Comment by kazlauskis** [comment]
This is OK now.
