### ISSUE TITLE
The map report shows everyones records

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#254]
It should show only the current user records. 

![Screenshot 2023-05-26 at 10 11 58](https://github.com/NERC-CEH/irecord-app/assets/7383162/ba4a44cd-3d1d-4ecb-845b-a58dc5b597dc)

**Comment by kazlauskis** [comment]
The report uses ES query using warehouse proxy with JWT authentication. 

@johnvanbreda you've mentioned you've done something with the `authenticated` JWT scope. Is this is linked to this issue? I am using the same website token as before which looks like this: 
```
{
  "aud": "86ff8b3a-4296-4e71-893c-8d0bd47e8f9a",
  "jti": "fb473428381e2f6434434c10dc38d1494a3783b6a91f391dfcc4113382010337c79bb7b1202599c4",
  "iat": 1685084837,
  "nbf": 1685084837,
  "exp": 1685184837.635118,
  "sub": "22738",
  "scope": [
    "authenticated"
  ],
  "iss": "https://irecord.org.uk",
  "email": "test@flumens.io",
  "email_verified": true,
  "http://indicia.org.uk/user:id": "97622",
  "field_first_name": "Flumens",
  "field_last_name": "Test"
}
```

**Comment by johnvanbreda** [comment]
Yes, I suspect that's the reason, since I default our mode to "reporting" when I get a scope of authenticated. That means all records, it seems I should have defaulted to "my records" instead. I'll do that now...

But, what I don't understand is the authenticated scope was not working on the warehouse - it was the reason the app was getting 500 responses since it's not a recognised scope from the warehouse' perspective. I wonder if previous versions of simple_oauth didn't pass the scope through, so when simple_oauth was upgraded it broke the warehouse.

**Comment by kazlauskis** [comment]
I don't know why the 500 was thrown, but the scopes haven't changed with this module update. Here is an old token generated last year:

```
{
  "aud": "2977a900-8c1e-4790-b940-0d027f8d9803",
  "jti": "d3f4671910274d0769728e0fdf7feee37d95869af34c55a422a3fc44496697a4f032a4dfe918b97a",
  "iat": 1651671692,
  "nbf": 1651671692,
  "exp": 1651771692,
  "sub": "1275",
  "scopes": [
    "authenticated"
  ],
  "iss": "https://butterfly-monitoring.net",
  "email": "test@flumens.io",
  "email_verified": true,
  "http://indicia.org.uk/user:id": "97622",
  "field_first_name": "Flumens",
  "field_last_name": "Test"
}
```

We can already use website-level JWT tokens to fetch everyone's records so I agree that the `authenticated` scope should return user-owned records only, at least for now so it fixes the apps.

**Comment by johnvanbreda** [comment]
There is a change - scopes is now scope - that's the cause of the broken behaviour as we detect scopes such as user, reporting, or verification to alter the range of websites available to the response. A JWT user token always limits to records you created, but as we didn't recognise the scope "authenticated" it broke the query which finds the websites to include in the response.

Fix on the way...

**Comment by kazlauskis** [comment]
Wut? 😄 they have changed the JWT attribute key without bumping up the package's major version. Thanks, can you support both variants for now, `scope` and `scopes`?

**Comment by johnvanbreda** [comment]
@kazlauskis that's done, and yes, it should cope with scope and scopes.

**Comment by kazlauskis** [comment]
works well now, thanks!
