### ISSUE TITLE
Improve text about joining activities

### ISSUE THREAD

**Issue by JimBacon** [NERC-CEH/irecord-app#255]
On the Activities page, selecting Read More shows the following:

> You can join in with more activities by visiting the iRecord Activities page.
> Pull to refresh the list.

'Pull to refresh the list' doesn't mean anything to me. Can you update this to explain how to do this - or maybe just have a refresh button?

**Comment by kazlauskis** [comment]
We are using the [pull-to-refresh](https://ui-patterns.com/patterns/pull-to-refresh) pattern here. I get this isn't intuitive, is that right? I could add a refresh button, but that page doesn't have an actual header to place it. Maybe a better option here would be to automatically update the activities page more frequently.

**Comment by JimBacon** [comment]
Ahh!!! 
Just change 'Pull to refresh the list' to 'Swipe down to refresh the list' and it makes sense (to me at least) and works.
When you only have two things in the list and want a third to appear a swipe is not an obvious thing to do.

**Comment by JimBacon** [comment]
Maybe even more clear is
'Close this help text then swipe down to refresh the list'
or
'Swipe down on the activity list to refresh it.'
