### ISSUE TITLE
Updates to app species dictionary

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#256]
We have a specific request to add the weevil Orchestes hortorum to the app. However, there may be a fault in the warehouse over this entry, see https://github.com/BiologicalRecordsCentre/iRecord/issues/1515 so it's probably best to wait until that is resolved.

More generally, can you remind me how the app interacts with the Indicia version of the UKSI - have all the changes made at the last major update been incorporated into the app? And I believe we are now making incremental updates to Indicia - will those feed into the app automatically or do we need to enable some periodic cross-checks to keep everything up to date?

**Comment by kazlauskis** [comment]
Apologies for the slow response. The process of importing the UKSI list from the warehouse into the app is a manual one and it requires an app update. Let me know when the species list settles down and I will sync the app with the warehouse.

**Comment by kazlauskis** [comment]
@kitenetter I've updated the species dictionary in the app but the _Orchestes hortorum_ is still missing. Do you know why?

The app uses `reports/library/taxa/taxa_list_for_app.xml` report with species list ID=15.

**Comment by kitenetter** [comment]
@kazlauskis I don't know why. Orchestes hortorum is [in the warehouse](https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/574132) and I can't see anything unusual about the way it has been set up.

**Comment by kazlauskis** [comment]
I don't have direct access to the warehouse to see what queries the report is executing, but maybe one of the web devs can have a look at why this report doesn't return the species? 

This is the species list I am receiving at the moment:

[response.json](https://github.com/NERC-CEH/irecord-app/files/13309580/response.json)

**Comment by johnvanbreda** [comment]
@kazlauskis I'll take a look...

**Comment by johnvanbreda** [comment]
@kazlauskis it should be there now. One of the search index tables had not been updated correctly, but I don't know why.

**Comment by kazlauskis** [comment]
Thanks!
