### ISSUE TITLE
Keyboard vibration - Android

### ISSUE THREAD

**Issue by robin-hutchinson** [NERC-CEH/irecord-app#257]
**Describe the issue**
Phone vibrates every time a character is entered for the Location field – even if all vibration settings on the phone are switched off

**To Reproduce**
Type in location field

**Expected behaviour**
No vibration on typing, especially if vibration settings switched off

**Screenshots**
![Screenshot_20230706-121112_Settings](https://github.com/NERC-CEH/irecord-app/assets/95474755/70971b87-b214-4d98-bcc4-a2083d7ad605)

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S1 5G
- OS: Android v.12
- App Version v6.0.5 (122)

**Additional context**
Only reproducible with Android

**Comment by kazlauskis** [comment]
@robin-hutchinson thanks. The haptics feedback was added for the location page to avoid people accidentally tapping on the map and changing the location without being aware of it. The core intention of it was to help the map use, but it affects if the location is changed through the GPS button or manually using the location input field. We can disable it for other than the map taps.
