### ISSUE TITLE
Enable habitat recording for botanical records more widely in app

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#259]
As far as I can tell, for botanical (and other?) taxa the option to record habitat information is only available in the specific case of a bryophyte species entered as a casual record, and here only 11 EUNIS level 1 habitat options (rather than then offering the additional EUNIS level 2 sub-menus that are available on the web = 57 options in total).

It would be great to have a habitat field on all bryophyte/vascular plant species recording in all app forms (casual record; plant survey; species list; bryophyte survey when available), and also enable the sub-menu options if this is possible (see attached list). Would this also be of interest for other taxa @kitenetter ?
 
[EUNIS for iRecord_Final.xlsx](https://github.com/NERC-CEH/irecord-app/files/12068313/EUNIS.for.iRecord_Final.xlsx)

**Comment by kitenetter** [comment]
It could be of interest for other taxa, although I'm not aware that other schemes have asked for it. The downside as always is that this would add a small amount of additional complexity to the app, even if it is something that is not mandatory for people to fill in.

I think it might be best to restrict it to the botanical species groups for now, although if it is easier to apply it to all app records then I don't have a strong objection to doing so.

**Comment by Sam-Amy** [comment]
I will close for now whilst I discuss further with BSBI; an historic article included reference to habitat data in the app, but I want to check this is still desirable.
