### ISSUE TITLE
Photos taken within the App not being accessible in phone gallery

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#261]
1) In the previous versions, these photographs were accessible through the file manager, and could be seen in the Gallery.
2) In the current version, these photographs are no longer accessible from outside the app. But the App is accumulating and using a lot of storage space. There seems to be no way of exporting the photo to the phone.”

**Comment by mikeprince** [comment]
I believe this has been implemented, however all the images are being stored in the root DCIM folder and not within a subfolder for iRecord. This should be changed to be consistent with pretty much every other app, and allow the images to be easily selectable.

**Comment by mikeprince** [comment]
Actually I think the Android standard is to store in a subfolder of Pictures rather than DCIM
