### ISSUE TITLE
app crashing after 20-30 seconds (related to Android Webview?)

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#262]
**Describe the issue**
iRecord app crashing every time it is opened; appears to be working normally for maybe 20-30 seconds, letting me click on records, start new records etc, but then it just closes instantly with no warning. This happened since about 13th Sept (until 3rd Sept did lots of recording and was working fine) and since then it has happened every time app opened. Sometimes it comes up with an error message saying that Android WebView is the cause of the crash (see screenshot).
 
Currently almost 500 records in the app waiting to be uploaded so is concerned about losing these. Both WebView and iRecord apps seem to be fully updated.

**Screenshot**
![Screenshot_20230921_102505_Device care](https://github.com/NERC-CEH/irecord-app/assets/104146164/1f4737eb-9129-4391-9532-709eafc0d342)
It doesn't show this every time the app crashes and the message itself closes very quickly. Hasn't tried uninstalling WebView yet as concerned about losing records that haven't been uploaded yet. Is this a possibility or is it OK to just try that?

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - OS: Android tbc
 - App version: tbc

**Comment by kazlauskis** [comment]
Thanks. I've found that this issue affects Samsung devices with Android 13. This is something that should be fixed at the device's system level. This affects the iRecord App and other apps but isn't directly related to our code, so unfortunately, there isn't anything we can do. In [this discussion](https://www.reddit.com/r/AndroidQuestions/comments/153kwo2/google_chrome_crash_webview_updates_help/), users are trying out various things...
