### ISSUE TITLE
Antispila petryi not available

### ISSUE THREAD

**Issue by robin-hutchinson** [NERC-CEH/irecord-app#264]
**Describe the issue**
The leafmining moth Antispila petryi is available to record on the web version of iRecord but missing in the species dictionary on the app
This species used to be lumped under treitschkiella but they were split out separately again a few years ago in a paper reviewing them
Currently it is not possible to record petryi on the app.

**Smartphone (please complete the following information):**
Reproducible on iOS and Android
6.0.7

**Comment by kazlauskis** [comment]
Thanks, the species list has been updated and will be available in the upcoming v6.1.0 release.
