### ISSUE TITLE
Sphagnum auriculatum missing from app

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#265]
Sphagnum auriculatum is available on the website forms (and via the Explore pages), but is not available on the app. May be related to this issue? [https://github.com/BiologicalRecordsCentre/iRecord/issues/1575](https://github.com/BiologicalRecordsCentre/iRecord/issues/1575)

**Comment by kazlauskis** [comment]
The app uses `https://warehouse1.indicia.org.uk/index.php/services/rest/reports/projects/irecord/taxa/taxa_list_for_app.xml?taxon_list_id=15` report to fetch the species list. This should be dealt with at the database level, and then I can pull in the latest species list into the app.

**Comment by kazlauskis** [comment]
@Sam-Amy is this one still relevant?

**Comment by Sam-Amy** [comment]
Yes, this is being dealt with under [https://github.com/BiologicalRecordsCentre/iRecord/issues/1575](https://github.com/BiologicalRecordsCentre/iRecord/issues/1575)
