### ISSUE TITLE
Recorder name missing when entering moth survey

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#268]
This has been reported by Marc Botham:

> The Recorder name is not auto-completing, it is simply remaining blank unless I input a name and because you cannot lock the name, I have to do this every time. This is on the moth recording form, but having just checked, is not the case when I just enter a record on the main iRecord form. I have also just tested entering data on the plant survey form and this also automatically enters my name as the recorder, so it appears to be limited to the moth recording form oddly.
 
I can't reproduce this on my app - for me the recorder name is always pre-populated.

**Comment by kazlauskis** [comment]
I can't reproduce this either. Is he using the latest v6.1.0 version?

**Comment by kitenetter** [comment]
I'll ask him to check. We can try logging out and in again as well.

**Comment by kitenetter** [comment]
Marc says:

> I just checked and I am on v6.1.0. I also tried logging out and in again. Sadly, no joy. What I think is more weird is that I don’t remember this being an issue earlier in year yet when I check all my unsubmitted records, the recorder name is blank in all of them. I can’t remember to be confident, but I feel like it wasn’t blank when I first inputted these records. Anyway, as I say, I am on current version and logging out and in hasn’t fixed the issue sadly, and as I said in previous email, this issue seems to be only in moth recording form.
> 
> I’m going to go through all my unsubmitted records and submit them so I don’t lose them, then I am going to uninstall and reinstall the app and see if that helps.

I'll close this issue for now. Will check what happens after Marc has reinstalled.
