### ISSUE TITLE
Is android 10 too old for the app?

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#269]
Is android 10 too old for the app? User tried to reinstall the iRecrod (and LERC Wales) app because the LERC Wales app they had been using was being very slow, and it says their phone is not compatable. 

**Smartphone (please complete the following information):**
 - OS: Android 10

**Comment by kazlauskis** [comment]
Android 10 should be OK but your device needs at least 3-4Gb of RAM.

**Comment by Sam-Amy** [comment]
Thanks, I'll pass that on

**Comment by Sam-Amy** [comment]
As you suggested @kazlauskis karolis, the issue was that the phone only has 1.9gb total memory and 456mb spare. I suspect this is not feasible but the user asked if there is any scope for releasing a lite version without the AI for those with cheap phones?

**Comment by kazlauskis** [comment]
The RAM requirement isn't so much about the AI but the camera and other essential features. For example, the operating system pushes the app to the background and often closes it when a user opens the camera app to take a photo for a record. We typically try to support at least over 90% of the market share, and devices with less than 3Gb RAM fall outside our current scope ([statistics ](https://www.enterpriseappstoday.com/stats/android-statistics.html#Android_Mobile_Statistics_by_RAM_Size)from a few years ago).

**Comment by Sam-Amy** [comment]
Thanks @karolis, I'll pass that info back.
