### ISSUE TITLE
AI classifier website endpoint returning 500

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#270]
The image classifier proxy is returning 500. Here are two logged errors from a single request:

https://irecord.org.uk/admin/reports/dblog/event/293
https://irecord.org.uk/admin/reports/dblog/event/294

@JimBacon do you know anything about this?

**Comment by kazlauskis** [comment]
`https://butterfly-monitoring.net/` and the ButterflyCount app are also affected.

**Comment by johnvanbreda** [comment]
I don't think Jim is available today - @DavidRoy do you know if anyone else can look into this? The error in the logs looks like it might be a server error at the classifier end.

**Comment by kazlauskis** [comment]
Yeah, I think the `https://waarneming.nl/api/identify-proxy` is returning 500.

**Comment by DavidRoy** [comment]
We'll have to wait for Jim. There was a new API that we need to switch to and I'm not sure if Jim has done this yet. The old one might be depreciated.

**Comment by JimBacon** [comment]
Johns' right, I'm not here! And no, I haven't done the work to switch to the new API yet. I did just try to call the Waarneming API directly from Postman and it was working. Has the app recovered, by any chance?

**Comment by kazlauskis** [comment]
It hasn't, but my direct calls to their API still fail with `{"message": "NIA not available (code: 500)"}`. I'm using this command:

```
curl --location 'https://waarneming.nl/api/identify-proxy/v1/?app_name=uni-jena' \
--header 'Authorization: Bearer XXX' \
--form 'image=@"/flower.jpg"'
```

@JimBacon the app fails softly at the moment - it simply doesn't show any suggestions, but otherwise, works fine, so this can probably wait until you're back.

**Comment by JimBacon** [comment]
When I do 
```
curl --location 'https://waarneming.nl/api/identify-proxy/v1/?app_name=uni-jena' \
--header 'Authorization: Bearer XXX' \
--form 'image=@"/lime-hawkmoth.jpg"'
```
I get a good response.

If I send an invalid token I get a response saying 'Incorrect credentials' and if I use an incorrect image path, curl throws an error. 

Do you still have a problem?

**Comment by kazlauskis** [comment]
It's working fine now. I understand the waarneming service was the issue here, so I am closing this ticket. Thanks!
