### ISSUE TITLE
Synonym Asplenium x microdon not showing on app

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#272]
Asplenium x microdon is listed as a synonym of Pyllitis scolopendrium x Asplenium obovatum = X Asplenophyllitis microdon (T. Moore) Alston in the UKSI, and is searchable on the website, but the synonym does not show on the app.

All seems to be as expected in the Warehouse ([here](https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-key=&filter-key_type=org&filter-taxa_taxon_list_id=136516&filter-taxa_taxon_list_id%3Ataxon=Phyllitis+scolopendrium+x+Asplenium+obovatum+%3D+X+Asplenophyllitis+microdon)). TVK = NHMSYS0100000679

**Comment by sacrevert** [comment]
App doesn't give synonyms as options
