### ISSUE TITLE
App treats recorder names differently to the iRecord website

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#276]
App records up to the end of 2023 were showing as recorder surname, firtname e.g. "Harvey, Martin C." (which matches the website), but since the beginning of 2024 it is using firstname surname e.g. "Martin C. Harvey". Ideally the app names would be consistent with the default behaviour of the warehouse (see iRecord issue [1520(https://github.com/BiologicalRecordsCentre/iRecord/issues/1520)).

@kazlauskis do you know why this has changed/how the app generates recorder names please?

**Comment by kazlauskis** [comment]
@Sam-Amy @kitenetter I understand from #215, the app is sending the correct recorder names, no?
> Can we standardise it so that it is always "Forename Surname"?

Records from 2023 are different because we have recently implemented the #189 task in the app. In other words, records older than 5 months have their recorder field filled in within the warehouse.

**Comment by johnvanbreda** [comment]
See https://github.com/BiologicalRecordsCentre/iRecord/issues/1027 - this may be worth revisiting.

**Comment by kitenetter** [comment]
We have abandoned #1027 which means that the default behaviour on the website will remain "Surname, First_name", and that this is pre-populated from the logged-in users' account (but that can be over-written if necessary).

I think that the app is currently producing records that also have the "Surname, First_name" format, so I'm not sure if there is still an issue here (leaving aside the older records).

At one point I said (in a now-closed iRecord issue):

> My records up to the end of 2023 are showing as recorder "Harvey. Martin C." (which matches the website), but since the beginning of 2024 it is using "Martin C. Harvey".

I think that is what led to @Sam-Amy raising the current issue, but things seem to have changed again.

Records in March 2024 were displaying as "Martin C. Harvey", but records from April 2024 onwards have gone back to "Harvey. Martin C.". So as far as I can tell things are currently working as they should.

So I'm going to close this.

**Comment by kazlauskis** [comment]
@kitenetter someone [asked about this](https://irecord.org.uk/forum/mobile-applications/recorder-name-not-displayed-correct-format) in the forum. In the app, I format currently logged-in recorder names as `Firstname Surname` (see https://github.com/NERC-CEH/irecord-app/issues/215), but I can easily swap these in the next app update.

**Comment by kitenetter** [comment]
As discussed above there are pros and cons to making such changes, but I agree that it makes sense to be more consistent and to change the app to `Surname, Firstname` to match the website default.
