### ISSUE TITLE
Geolocation error message, despite being switched on in app

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-app#279]
A user has emailed with this issue - details of device to follow.

**Describe the issue**
Geolocation error message despite being switechen on in the app and pther geolocating apps working.

**To Reproduce**
Try to geolocate and get error message.

**Expected behaviour**
Geolocation to work when it is switched on on the app.

**Screenshots**
![image](https://github.com/NERC-CEH/irecord-app/assets/104146164/72d7a48b-4833-4f56-89bd-01e042bcb16f)
![image](https://github.com/NERC-CEH/irecord-app/assets/104146164/fd6745bb-c5d1-415d-8bf5-514f0cd9510e)

**Smartphone (please complete the following information):**
TBC

**Additional context**
Several of my apps use the location which in my settings is definitely on. No problem with NBN location or OS maps, but Irecord is not there as one of the apps using "location" . It is definitely switched on on the Irecord app itself, as you can see

**Comment by kazlauskis** [comment]
@Sam-Amy they most likely haven't given the location permissions to the app. The option in the screenshot showing the geolocation ON, means the app geolocates list survey occurrences. They should go to the android settings, find the app and grant the location permission.

**Comment by Sam-Amy** [comment]
Thanks Karolis. I've suggested and will close once they confirm this works.

**Comment by Sam-Amy** [comment]
This worked, the user was very grateful - thanks
