### ISSUE TITLE
Question re app records and surveys

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#281]
@kazlauskis can you let me know the difference between the "iRecord App" survey (ID = 374) and the "iRecord App General Survey" (ID = 576)? Do individual records go into iRecord App, and the lists associated with the survey options go into iRecord App General Survey?

If so, do all three surveys (plant, moth, species list) all go into iRecord App General Survey?

**Comment by kazlauskis** [comment]
@kitenetter Yes, the "Species List Survey" as it is called in the app is `576`, and each survey has its own ID, like the plant one uses `325` and moths use `90`.

**Comment by kitenetter** [comment]
Thanks - closing.
