### ISSUE TITLE
Plant survey: species records phone GPS option 

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/irecord-app#287]
Even after setting a location for the survey as a whole the species records pickup the phone GPS. This is rather frustrating if one is just using the app to enter data after a survey. Perhaps this should be a survey-level option to switch on or off.

**Comment by sacrevert** [comment]
Ok, just seen that this is under global settings. I wonder whether it would be better in the users' face though?

**Comment by kitenetter** [comment]
@sacrevert there's quite a lot of discussion around this under #263 and I think we should review this when we meet with @kazlauskis. Maybe close this issue?

**Comment by sacrevert** [comment]
Cheers Martin, that looks like it covers it exactly 👍
