### ISSUE TITLE
Fuzzier matching of taxon vernacular names

### ISSUE THREAD

**Issue by japonicus** [NERC-CEH/irecord-app#33]
Searching using taxon common names  currently requires a match at the beginning of the string, which misses many expected matches.

e.g. a search for 'Squirrel' should include 'Grey Squirrel' in the results

maybe consider matching from the beginning of any word when looking for vernacular name matches.

**Comment by kazlauskis** [comment]
Good one, that shouldn't be too hard to add and it would be very useful.

**Comment by AugustT** [comment]
I still have this problem ie 'woodpecker' brings up nothing

**Comment by kazlauskis** [comment]
I agree, this also links to #16 we need to improve the searching.
