### ISSUE TITLE
Species name lost when syncing to website

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#41]
My records are syncing with the web but only recording the genus....The species name has been lost.

**Comment by kitenetter** [comment]
Same is happening for me for both records I have entered so far, e.g. this record which was recorded as Phytomyza ilicis (and has that name correctly assigned on the phone itself): http://www.brc.ac.uk/irecord/record-details?occurrence_id=2959738

**Comment by kitenetter** [comment]
Hi @kazlauskis - just wanted to flag this one up as high priority, because it is resulting in incorrect records being passed to iRecord. Thanks.

**Comment by kazlauskis** [comment]
Sorry, I was away for a week. Thanks for reporting. I totally agree, this is top priority - I will try fixing it asap.
