### ISSUE TITLE
Lost records

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#42]
A couple of records haven't appeared on the website but are locked and flagged as uploaded according to the app. I submitted these on a slow connection, so not sure whether that had something to do with it?

**Comment by kazlauskis** [comment]
If possible, could you please let me know the exact time you have submitted the records as I will then try to find the problem through the logs.

**Comment by davidgenney** [comment]
Sorry, I can't remember the exact time but it would have been pm on the 5th March.  The records were for Lecanora conizaeoides and Physcia adscendens (lichens). It would be nice to get the photos back but not the end of the world!

**Comment by davidgenney** [comment]
Hi Again. A related but different bug to report under this heading today I'm afraid. This morning I added about ten records of Lobaria lichens to the App. The App closed because I looked at something else on my phone. When I re-opened it, all of my records have disappeared. It's not great shakes, I can go and record them again, but it's the sort of bug that makes me nervous for days I'm recording records I won't be able to repeat. I hope this is something obvious! Thanks.

**Comment by kazlauskis** [comment]
Thanks David, I would like to know more on how this has happened as it can be very hard to discover what triggers such behaviour without knowing the exact sequence of actions. 

1. Did you turn it off completely or just switched to another app - i.e. when returned, did you see the splash screen when opened the app again?
2. Also, did you add all the records in one go or did you switch to other apps in the meanwhile
3. Did you add any photos to those records?
4. Were the records flagged for submission - paper plane icon?
5. I wonder how long the app has been open for?

 Let me know if there is something else that comes to your mind.

**Comment by davidgenney** [comment]
**_I'll do my best..._**

1. Did you turn it off completely or just switched to another app - i.e. when returned, did you see the splash screen when opened the app again?
_**_I didn't turn it off but the screen obviously timed out from time to time so I had to unlock and click on the app again. This took me to where I left off without the splash screen and all ok. However, we then stopped for a snack and I took a couple of photos of the kids. When I next activated the phone to make a record I clicked on the app short-cut and it did re-start at the splash screen. That was when I noticed none of the day's records were there anymore. _**_
2. Also, did you add all the records in one go or did you switch to other apps in the meanwhile
**_Records added one at a time at different times over about an hour. See comment about switching to camera above though._**
3. Did you add any photos to those records?
**_Yes, to most of them but not all. I did this by linking to the camera from the app rather than by taking a photo and then adding it from the gallery._**
4. Were the records flagged for submission - paper plane icon?
**_No, they weren't._**
5. I wonder how long the app has been open for?
**_About an hour, perhaps a bit longer._**

**_The only other thing to note is that although none of the records were saved, the locality name has saved in the locality history... it was locked so is added to new records at the moment._**

**_I hope this helps and perhaps it was just a one-off.  I'll keep testing...._**

**Comment by kazlauskis** [comment]
That's great, this helps me a lot. Somehow I don't think this is a one off, I will check it asap. Thanks!

**Comment by kazlauskis** [comment]
I think this closely relates to #58

**Comment by davidgenney** [comment]
Hi Karolis, I've tried to replicate this issue i.e. by closing the app and taking photos etc.. but no loss of records so far.  One thing I did notice though is that my phone's internal memory was very low - just in case that's relevant.

**Comment by davidgenney** [comment]
Hi again Karolis, 
This bug just happened again at about 8.15 pm today. I had entered about 20 records without photos. I switched to the camera via the phones home screen, took a photo and when I returned to the app at previous records had gone. 
Good luck!

**Comment by kazlauskis** [comment]
Hi David,
What is the app version you are using? Menu->About (bottom of the page)

**Comment by davidgenney** [comment]
Hi Karolis,

It's v1.0.0 (beta 5).  I'll update to the new version you sent earlier
today. Sounds like you've made some good improvements.

All the best,

Dave

**Comment by kazlauskis** [comment]
Hi Dave,

I hope it was a good fungi season for you :mushroom: I wonder if you had any more issues with records being marked as sent but actually not on the iRecord website?

Also, have you had any more records being deleted on your device recently?

Thanks!

**Comment by davidgenney** [comment]
Hi Karolis,

Yes, it was a good season and thanks to the app I even managed a good
handful of records while out with the family!

I haven't had any problems with either issue recently.  Congratulations,
you've developed a cracking and robust app.

My only issue now is that the British Mycological Society now have in
bespoke indica page modelled on iRecord but I can't transfer mt irecord app
records across. Not an issue for you to sort out though.

Let me know if there's anything else you'd like me to test.

Thanks and all the best,

Dave

On Tue, 17 Jan 2017, 11:44 a.m. Karolis Kazlauskis, <
notifications@github.com> wrote:

Hi Dave,

I hope it was a good fungi season for you 🍄 I wonder if you had any more
issues with records being marked as sent but actually not on the iRecord
website?

Also, have you had any more records being deleted on your device recently?

Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NERC-CEH/irecord-app/issues/42#issuecomment-273117775>,
or mute the thread

**Comment by kazlauskis** [comment]
That's great, thanks!
