### ISSUE TITLE
Photograph location and preview

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#43]
1) Photos taken within the app do not appear in my phone's gallery and I can't find then anywhere in my phone directory. Ideally I would want access to the full resolution images.

2) Linked to the above, it would be nice, but not essential, to be able to click on the thumbnail of pre-submitted records to see a higher resolution version. This could be solved by dealing with 1) perhaps.

Thanks,

Dave

**Comment by AugustT** [comment]
I have the same issue. I cannot find images taken in the app to use elsewhere

**Comment by kazlauskis** [comment]
This links to #51 I will add a photo preview on the app.
