### ISSUE TITLE
'Certainty' field missing

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#44]
Would it be possible to add the 'certainly' field into the app? 95% of the time I record as 'certain' but there hare occasions I can't remember the full name of a species in the field. In such cases I would enter a genus and mark as uncertain to prompt me to update on the web page once I have access to literature.

I was almost going to suggest being able to submit a record without a species name for such situations, but this could result in people uploading lots of photos without an id, so perhaps best avoided.

**Comment by kitenetter** [comment]
One problem with this approach is that it makes extra demands on those verifiers who verify records the moment they arrive on iRecord - they might verify the record at its initial genus level and then have to re-verify once it is fully identified. I wonder if what we actually need is a way that recorders can flag a record as 'unfinished', and that such a flag would prevent the record being exposed for verification, until such time as the recorder marks it 'finished'?

**Comment by davidgenney** [comment]
Good point. I don't have that problem because nobody is verifying the groups I record but a can see it could be a problem.

**Comment by kazlauskis** [comment]
OK, I am closing this one, because we might need an unfinished flag more than certainty one.
