### ISSUE TITLE
Record with photo not uploading first time

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#47]
I made a record this morning and took a photo (using the camera button within the app): http://www.brc.ac.uk/irecord/record-details?occurrence_id=2959740

The first time I tried to upload the record the plus sign was spinning for around 10 minutes before it reverted to a red paper airplane. When I tried submitting it again it uploaded okay.

Maybe a one-off glitch, will test again later.

**Comment by kitenetter** [comment]
This problem has not re-occurred.

**Comment by kazlauskis** [comment]
Maybe there was poor connection at that time. It times out if there is no response from the server, but I think it shouldn't wait for 10 min. I will change the timeout duration.

**Comment by kazlauskis** [comment]
I have decreased the submission timeout, so it should not show the spinning icon (sending) for that long. 

The general submit functionality was improved in 6558e1f4b1d1b66e843ba45e62a3a82026e3623c
