### ISSUE TITLE
Photo auto-rotation?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#48]
The photo for this record: http://www.brc.ac.uk/irecord/record-details?occurrence_id=2959740

was taken as a portrait photo, but the app has treated it as landscape. Not sure if this is a result of how the app handles photos or whether my phone misinterpreted the photo to start with.

**Comment by AugustT** [comment]
I also have this issue, pretty sure it is not a problem with the phone.

**Comment by davidgenney** [comment]
I also have this issue when I upload directly to the website if that helps.
