### ISSUE TITLE
Editing the Number attribute on the iRecord website

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#49]
The "Number" attribute in the app does not appear in the record editing form on iRecord, so cannot be changed. Is there a reason why the app's "Number" attribute can't be imported directly into the website's "Quantity" attribute, from where it would be editable?

**Comment by kazlauskis** [comment]
I think this issue mostly belongs to iRecord website's recording form. I also think it should take into account what type of number (range or simple number) the record comes with. I will look into this.

**Comment by johnvanbreda** [comment]
Presumably the iRecord app submits records into it's own survey ID as it has slightly different attributes. Therefore, it would be better to have an app specific recording form on the website for editing app records, which points to the correct survey ID to match the app (and therefore match the attributes). This means app records should submit sample.input_form with the path of this app specific recording form.

**Comment by kazlauskis** [comment]
Fixed
