### ISSUE TITLE
Number attribute: use of ranges

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#50]
I would prefer to be able to type in, or pick, an actual number, rather than use a number range. This is partly because I want to be able to record what I've seen as accurately as possible, and partly because having ranges in the Number field will make life more difficult for those recording schemes who may later download the data from iRecord. Some of the data management systems used by recording schemes do not accept ranges as an abundance measure, so that if the app was to generate lots of data with ranges this will be an additional data management burden for at least some of the recording schemes.

**Comment by kazlauskis** [comment]
Yes, I think we could provide a number slider as an option.

**Comment by japonicus** [comment]
Typed values might be easier because the range of useful values could be
very broad (e.g. seven orchids v's 15 000 starlings). Accurately capturing
that with a slider could be quite awkward.

**Comment by DavidRoy** [comment]
Ultimately, it would be preferable for the occurrence attributes (including quantity) to relate to the taxon being recorded (e.g. quantity for a plant is very different to butterflies).

But a short term solution might be a free text box to indicate the exact number or a range, in addition to the current option to give a range.

**Comment by kazlauskis** [comment]
OK, that's even easier.
