### ISSUE TITLE
Duplication of a record

### ISSUE THREAD

**Issue by johnvanbreda** [NERC-CEH/irecord-app#53]
Last weekend I collected a record of Common Limpet using the app and posted it to iRecord. I have only 1 such record in the app and have not deleted any, but today I noticed that I have 2 duplicate records in My Records on iRecord. IDs are 2959075 and 2957792. 

I don't remember what I did, but it's possible that I tried submitting when I had a poor connection, then tried submitting again later from home.

**Comment by davidgenney** [comment]
I have managed to duplicate a record upload too on the website, but on purpose to test the app. I originally sync'd my record 2968020 however today when I went back to the app, this record wasn't shown as synced. I re-synced it and it has appeared on the website as a new record 2969831. Note that I had added the species name to the first record as per previous bug report. 
There is also a problem with location names being dropped from app records but I will log this separately.

**Comment by davidgenney** [comment]
This issue has resulted in 56 duplicate records on the iRecord website from my recording.  Just to let you know, I've sent a list of the duplicates to irecord@ceh.ac.uk to ask for them to be deleted.
All the best.

**Comment by grahamcheckley** [comment]
I have created duplicate records on iRecord in the past from iRecord butterflies.  This was due to 3G transmission problems, I now tend to wait untill I get home and use a WIFI connection.

Best regards
Graham

**Comment by kazlauskis** [comment]
Thanks Graham. I agree, it is best to submit the records only with a stable network connection until we fix the issue.

**Comment by kitenetter** [comment]
I was about to report that a record has been duplicated again, which was the case when I checked iRecord a couple of days ago, but looking at it again today the record has now become triplicated, which seems very odd.

The record numbers are 3815860, 3816746 and 3822566:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=3815860 - uploaded 6th August 2016 at 21:37
http://www.brc.ac.uk/irecord/record-details?occurrence_id=3816746 - uploaded 7th August 2016 at 09:10
http://www.brc.ac.uk/irecord/record-details?occurrence_id=3822566 uploaded 8th August 2016 at 07:39

The first of those records has the correct date for the upload I actually initiated. I have no memory of doing anything with the app subsequently to cause a repeated upload.

As far as I'm aware there was no interruption or other odd behaviour during the original upload, which was done from home while linked to wifi, and another record uploaded at the same time went through okay, only the above ended up being triplicated.

**Comment by kazlauskis** [comment]
Thanks, yes it can happen multiple times. Has the record status changed to 'uploaded' on the app with the first submission?

**Comment by davidgenney** [comment]
Hi Karolis,
I've been testing the latest version you sent me a few weeks ago (30th August). I'm afraid there's still a problem with duplication, for example see my records 4173799 and 4173793. I was syncing via a WiFi network but it was slow and some of the records, particularly those with photos, were failing to sync first time and came up with a red icon. I wonder if these are the duplicated records? Is there any chance duplicates could be deleted for me please?
Thanks,
Dave

**Comment by kazlauskis** [comment]
Hi David,

Thanks, I haven't had the time to fix this issue, but I will do it once I have some spare moment. I will also delete all the duplicates myself. I can detect them and do it automatically on the database as all the duplicates share the same app-record-id. 

Thanks 👍

**Comment by davidgenney** [comment]
Brilliant, thanks Karolis 😊

**Comment by kazlauskis** [comment]
I have just deleted the duplicates. For a more permanent solution it is not implemented yet because it involves a fair amount of thought and testing so that it would not break other apps. I will do it soon though.
