### ISSUE TITLE
How is recorder name worked out?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#54]
On iRecord I am registered as "Harvey, Martin C.", and that name is what I use for all my records. Records arriving via the app are being assigned to "Harvey, Martin" without the middle initial.

The app itself doesn't seem to allow any control over recorder name, so presumably iRecord is somehow calculating the name from my account, but I don't know why it is ignoring the middle initial.

Not exactly a life-or-death issue, but it is annoying that the app records are inconsistent with all my other records.

**Comment by kazlauskis** [comment]
I agree, this should not modify your name. I will look into this.

**Comment by MNSmith** [comment]
Might need a decision at the iRecord end of things about how names are displayed.  "Surname - Firstname" is the "traditional" way names were displayed in Recorder 3 and BRC seems to have stayed with this.  I would much prefer all names on iRecord to be displayed as "Firstname - Lastname" as currently we have a mixture of styles depending on how the record is input into iRecord - different pages or input forms do different things.  Needs consistency across iRecord itself.

**Comment by kazlauskis** [comment]
@MNSmith I think you should create an issue on the [iRecord issue tracker](https://github.com/BiologicalRecordsCentre/iRecord/issues) for the consistency of the names with the examples of those input forms that treat it differently.

**Comment by kazlauskis** [comment]
Issue is addressed on iRecord website tracker.
