### ISSUE TITLE
Location names lost

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#58]
I was recording at speed on Monday and didn't have time to add the location name at the time the record was captured. I retrospectively added the site name and successfully uploaded to the web as record 2968026. I edited the record on the web (added the species name) but now when I look at the record on the app it has lost the location name and isn't flagged/locked as uploaded.

**Comment by kazlauskis** [comment]
That's not good, there might be some record status updating issues, that I need to take a look into. Thanks for reporting it.

**Comment by davidgenney** [comment]
Just as another example, I've created a [screen shot](https://goo.gl/photos/YDkfCnrKnm5riLSE8). The bottom two records have both been uploaded to the web database as 2965691 and 2968017. The first has lost it's name and the second just isn't registered as uploaded. Thanks for looking into it.

**Comment by kazlauskis** [comment]
Yes, that must be fixed asap as the app creates duplicates on the database. I will clean those afterwards. Thanks for the screenshot!
