### ISSUE TITLE
Order of records in the app.

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#60]
Records don't seem to stay in chronological order in the app.  It would be useful if they did so that records captured at the same time can easily be managed/viewed. For example, I captured a series of records on the 14th and one of them has disappeared to the bottom of all my app records and appears before records made on the 6th.

**Comment by kazlauskis** [comment]
I wonder if you have changed that record's date to something other than current date?

**Comment by davidgenney** [comment]
I don't think I have, unless I'm missing something.  Here's a [screen shot](https://goo.gl/photos/YDkfCnrKnm5riLSE8) that shows the records are not in chronological order.

**Comment by kazlauskis** [comment]
Hehe, yes it's a bug. I will fix it.

**Comment by kazlauskis** [comment]
Added record sorting by record creation time.
