### ISSUE TITLE
Crashing from time to time when uploading photos from phone gallery

### ISSUE THREAD

**Issue by davidgenney** [NERC-CEH/irecord-app#61]
I did some monitoring work on Monday.  The app crashed a few times when I added photos to the record from the phones gallery (which I did to keep the full resolution photo on my phone). It didn't crash every time so I don't know whether it's a bug or just something to do with resources on my phone? Thought you should know though. In each case the record had been saved when I restarted the app so nothing lost.

**Comment by kazlauskis** [comment]
OK, thanks for letting me know. Could you please tell me what is your Android version?

**Comment by davidgenney** [comment]
Silly question but do you know how I find out which android version? I have a galaxy S5 bought last autumn if it's obvious from that. Cheers

**Comment by kazlauskis** [comment]
No worries, here is a video that could help you:
[Youtube Galaxy S5](https://www.youtube.com/watch?v=fpaiNwHzD0s)

**Comment by davidgenney** [comment]
Ha, I should have been able to work that out. I'm on version 5.0. Ta!

**Comment by kazlauskis** [comment]
Closing this one since no one else has reported this again.
