### ISSUE TITLE
Incorrect taxon recorded after submission

### ISSUE THREAD

**Issue by johnvanbreda** [NERC-CEH/irecord-app#63]
Last week I recorded a 7 spot ladybird and noted here the difficulty I had selecting the common name, so used the latin name. In the app I have a record of Coccinella septempunctata, but the record in iRecord is http://www.brc.ac.uk/irecord/record-details?occurrence_id=2968457 which shows that it was originally submitted as just the genus Coccinella and the verifier had updated the name to include the species name. 
So it looks like my record of C. septempunctata was actually changed to just Coccinella on submission.

**Comment by kazlauskis** [comment]
Same as #41
