### ISSUE TITLE
Species aggregates can't be distinguished from narrow sense (sensu stricto) names

### ISSUE THREAD

**Issue by japonicus** [NERC-CEH/irecord-app#65]
There are various instances where two versions of a taxon name exist. A broad version (which lumps together multiple species concepts), denoted with an 's.l.' or 'agg.' suffix, and a narrow version of the name - without a suffix or with a 's.s.' suffix.

Where these name variants exist they need to be treated separately, both names need to remain available for new records and to be distinguishable.

Currently the app appears to strip the suffix - so that names such as Trichophorum cespitosum appear on the list twice, but the s.l. and s.s. names can't be distinguished.

**Comment by DavidRoy** [comment]
I also found this when trying to enter Erophila verna.  Several entries for the species name and multiple entries for the varieties etc
