### ISSUE TITLE
GPS dosn't refresh properly with location locked

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#66]
I find that if I lock my location, the GPS location updates for the next record but for no records after this.  The location name is set properly but the grid reference dosn't update no matter how far I move.

Also, could someone please tell me how to download the Android app from Google Play?

Best regards
Graham

**Comment by kazlauskis** [comment]
Yes, I have also noticed that it was sometimes hesitant to update the GPS coords. I will look into this.

**Comment by kazlauskis** [comment]
The app is currently available for testing and so is only reachable by a private URL that we have distributed to some people. Which I guess you have also received since you have been trying the app, is that right? Otherwise, if you let me know your email, I will resend you the URL.

**Comment by grahamcheckley** [comment]
Dear Karolis

Please send me the link

Best regards
Graham

**Comment by grahamcheckley** [comment]
Woops, my email address is grahamcheckley88@gmail.com

**Comment by grahamcheckley** [comment]
I think this is now working OK.  Thank you!
