### ISSUE TITLE
Locking site name separate from grid-ref?

### ISSUE THREAD

**Issue by FJRoberts** [NERC-CEH/irecord-app#68]
Does this relate to #66? How does locking of locality name and grid-ref work?
It seems that I can't lock these two as separate items... but I might well be misunderstanding what's going on.
In a large site, e.g. "Great Wood, Keswick", I'll want the grid-ref to alter for each new record within that large site. But there isn't (AFAICS) a means to lock locality name but allow GR free... Or is there?

Excuse my confusion... and thanks for elucidation.

Jeremy.

**Comment by kazlauskis** [comment]
Hi Jeremy,

Yes, you are right, you can't lock Grid Ref independently from location name, **unless** you lock GPS acquired coordinates and location name. That means, if you set a location using a map or grid reference it will lock your location and location name together for next records. But if you lock GPS tab coordinates and location name, then the GPS will be run every time a new record will be added, but the location name will be pre populated for you, therefore locking just the location name. 

So you can walk around a big site and give it a name and location coordinates should be updated on new records using GPS.

**Comment by FJRoberts** [comment]
Oh yes!  :-) - took a while to get my addled brain round what you were telling me. Thanks, Karolis! Getting there....
