### ISSUE TITLE
Geo-location Coordinates of uploaded records.

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#69]
When used in the field, the app happily generates an OS Grid reference.  When the record is uploaded the information that appears in "Grid Ref" field is displayed in Lat-Long coordinates and the OS grid ref is "hidden" in a field called "Gridref_calculated".

The "Grid Ref" field is the field that is displayed in the verification grid and the expectation is that this will be an OS Grid Reference.  While the Lat-Long may be correct, a) it is very hard to read "by eye" when verifying a record while and OS Grid Ref is more understandable and more easily checked and b) If the data is downloaded from iRecord, having Lat-Long coordinates complicates matters and may not be useable by some software that expects to see and OS Grid Ref.

Can we have an OS Grid reference in the "Grid Ref" field please.

Thanks

Matt

(Copied over from the iRecord forums as GitHub needed about 4 attempts to send a verification e-mail to me)

**Comment by kitenetter** [comment]
There are good reasons to store the lat/long but I agree that the grid ref needs to be shown as the primary reference for verifiers and in downloads. We have this on our wishlist for improvements to be made to the iRecord download functionality.

**Comment by kazlauskis** [comment]
This is an iRecord website issue.
