### ISSUE TITLE
Editing records uploaded from the app.

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#70]
If I submit a record via the app, I can edit this record through iRecord.  When I do, it takes me to the "Enter a list of Records (for a date)" page which means I need to swap between tabs for species and location.  For an individual record, I think it would be more useful if it linked to the "Enter a casual record" page for editing purposes, all of the field are on a single page here.

**Comment by kitenetter** [comment]
I think what we are likely to do is to have an iRecord form specific to the app, that will allow editing of all the data relevant to the app records. To be confirmed once the app is nearer finalisation.
