### ISSUE TITLE
App functionality wishlist.

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#71]
I would like to see the following functions in the app:

a) User defined "favourite" species lists that I can scroll through, select Species 1, Species 2 and Species 4 and have the app generate 3 records but only have to fill in the location data once.

b) The facility to lock/remember location names.

c) Dynamic pages for different groups, if I record a bee then I get presented with the various fields BWARS would like to see.

**Comment by kazlauskis** [comment]
Thanks, I think this relates to some other issues.

a) I have created a new feature request #72 regarding favourite species. The 3 records with one location relates to #67 
b) you can lock location name. On location page you can click on the lock icon (top-right) and this would lock you grid ref/map location + location name. But if you acquire your location through GPS then only the location name will be locked and subsequent records will try to get fresh new GPS coords.
c) #14

**Comment by MNSmith** [comment]
The solution to the request to lock the Location name sounds like it will do what is needed, I will be able to add a name but still move about a bit.

How long does this "Lock" feature remain operational.  If I exit the app and restart it later, will the lock remain as it was or will stopping /starting the app clear it.

If the Location remains locked, some indication on the main screen of the app (red licgt/green light) might be helpful to indicate this.

**Comment by kazlauskis** [comment]
Hi, yes the location will remain locked between sessions. The app currently shows the lock symbol next to the attribute that is locked, but that is only on the record edit page. Yes, it might be a good idea to display it also on the home page record listings, but I need to find where to squeeze this in first. Thanks!
