### ISSUE TITLE
Indicating locked attributes on listed records

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#73]
A follow up to an earlier (now closed) query (#71) regarding the facility to local a location name.

The solution to the request to lock the Location name sounds like it will do what is needed, I will be able to add a name but still move about a bit.

How long does this "Lock" feature remain operational.  If I exit the app and restart it later, will the lock remain as it was or will stopping /starting the app clear it.

If the Location remains locked, some indication on the main screen of the app (red light/green light button) might be helpful to indicate this so the recorder can check.

**Comment by kazlauskis** [comment]
Hi, yes the location will remain locked between sessions. The app currently shows the lock symbol next to the attribute that is locked, but that is only on the record edit page. Yes, it might be a good idea to indicate locked attributes on the home page record listings, but I need to find where to squeeze this in first. Thanks!
