### ISSUE TITLE
Using Take Location from Map makes GPS stop working

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#74]
I used the Take Location from Map today with Location locked to preserve the location name.  That worked fine but my subsequent records kept the same grid reference rather than where I then was.

I can get the GPS to start working again by manually refreshing GPS for a record.

**Comment by kazlauskis** [comment]
Hi Graham,

The location and location name are both locked if a map or grid reference is the source for the location. It is only GPS source locked locations that are refreshed on subsequent records.

**Comment by grahamcheckley** [comment]
Understood.
