### ISSUE TITLE
Record upload problem - no location name

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#76]
I have a record on the app that does not upload to iRecord.  It has a GPS location but no location name.  It appears the lack of location name is preventing record upload.

One of the "nice to have" features discussed earlier was the ability to upload records to the server with a GPS location but without the requirement to have a named location input at the time of recording - this could be added or amended later via iRecord itself.  Useful if you are in the middle of the countryside and do not know the nearest named location.

Could we have this considered for a fix please.

**Comment by japonicus** [comment]
There is discussion about the requirement for location names here: #45

**Comment by kazlauskis** [comment]
You can lock the location name, so you don't have to re-enter it on every record.

**Comment by MNSmith** [comment]
Ok - having looked at #45 and the other comments, neither addresses the point of my original query.  Having the ability to locak a location name us useful, but of no use in this instance if no location name is given.

While I agree that a location name is a useful aid to verification, I am still looking for this app to be essentially a quick way of recording in the field.  It has already been discussed that a) entering location names on a small phone screen can be tricky and time consuming and b) recorders may not know where the nearest relevant place name is to the record, particularly if they are in unfamiliar or sparsely populated areas.

I would really like to see this app be just a "point and click" recording method in the field - here I am, I see species X - I record it and the GPS provides the location.  If I have time or the knowledge, I can, if I want, add the location name at the point of record.  However, what I had hoped is that records without the location name could be uploaded to iRecord and any location name details could be added later, when perhaps it is more easy to look at the map on screen and give a location name.

If iRecord is going to require a location name (and some of the names I have seen during verification are essentially useless), then perhaps these uploaded records could be "held" at the iRecord end with a flag on the record visible to the recorder saying "Needs a location name in order to be verified - please edit the record" or similar.  This gives the recorder the chance to sort things out and add info which he may not know in the field.
