### ISSUE TITLE
Splash screen still says beta

### ISSUE THREAD

**Issue by charlesroper** [NERC-CEH/irecord-app#80]
The splash screen on the release version is still saying beta. Screenshot: https://goo.gl/photos/3PcAfGRvejpRksjZ6

(also, minor point: on the contributors page would it be possible to put (FSC) after my name please?)

**Comment by kazlauskis** [comment]
Hi Charles, yes I have noticed the mistake only after I have pushed the app for app store review, haha. Thanks, I will update it with the next release.

**Comment by kazlauskis** [comment]
BTW, we have added the activities functionality you have requested. This will come with the next release as well.

**Comment by charlesroper** [comment]
Awesome, thanks! I was reading that thread a little earlier actually. Should make the app super-useful for us here at FSC.
