### ISSUE TITLE
Ability to lock location name, but not GPS coords

### ISSUE THREAD

**Issue by BlueCarbon7** [NERC-CEH/irecord-app#81]
I created some app records whilst on a walk. I didn't submit them at the time as I didn't have time to enter the location name on each individual record.

At home I entered the location name for one record. On the next record I noticed the 'past' option. I then went through the other records and clicked on this past option to set the location name. What I hadn't realised is that not only does this set the location name, it also overwrites the original GPS coordinates with the original record entry!

I think it would be a good idea to separate the location data field into two fields, one for the location information (GPS, map, etc) and one for the location name (manually entered). This would allow  you to 'lock' the location name, but have variable location information for that same location name. the two items together make up the 'Location' info.

Then, you can 'lock' the location name whilst at a geographic location, but have more accurate location information. The app can submit the data as one field to iRecord , but it's a combination of the locked location name and the changing location data.

**Comment by kazlauskis** [comment]
Heya, I think these two issues should help you: #45 #68

**Comment by japonicus** [comment]
The behaviour of the 'Past' button does seem odd to me, as it's unclear that it is copying both placename and gridref.  Under what circumstances would it be desirable to overwrite one gps gridref with another?

Anther problem (which maybe should be a separate bug) is that grid-refs that are copied across using the 'past' button are still tagged as coming from a GPS - even when that is no-longer the case (as the ref has been copied rather than directly assigned).

**Comment by kazlauskis** [comment]
When copying GPS sourced past location only the location name is copied and the coordinates should be refreshed though GPS.

**Comment by japonicus** [comment]
Not when I tried it just now (nor is that what @BlueCarbon7 describes).  If
you add a record with a GPS'ed location, then later go back to it, click
the past button and choose another named location (that has an associated
gridref) - then both the location name and grid ref are overwritten.

(n.b. using the 'past' button not locking)

**Comment by BlueCarbon7** [comment]
The 'past location' option does overwrite the recorded GPS location value with the GPS location from the original records' data. That is exactly why I logged this issue. If using 'past location' had kept the recorded GPS location for that record, but overwritten just the location name with the original records location name that is the behaviour I expected and would wanted.

**Comment by kazlauskis** [comment]
Yes I see what you mean. I have created a new issue to move our discussion there #83
