### ISSUE TITLE
No option to add 'sex' of record

### ISSUE THREAD

**Issue by BlueCarbon7** [NERC-CEH/irecord-app#82]
There is no option to add the sex for a record.

**Comment by kazlauskis** [comment]
Agree, it could be useful, though I don't know if this should be added to a default record form. Dynamic attributes that we are planning on adding in the future should provide this attribute for some species groups where recording a sex is needed #14

**Comment by BlueCarbon7** [comment]
All the record entry forms on the iRecord website have a 'sex' field, so it would seem to make sense to use the same field structure in the app. Maybe just make it an optional field, rather than a mandatory field where you then have to offer an 'unknown' option as well?

**Comment by kazlauskis** [comment]
Closing as this should be fixed with #14
