### ISSUE TITLE
Indication what what activity you're entering data into

### ISSUE THREAD

**Issue by charlesroper** [NERC-CEH/irecord-app#88]
There's currently no indication of what activity you're currently entering data against unless you go into the Activities screen to check. This could make it quite easy enter data in the wrong activity by mistake, especially if you exit the app and come back to it some time later.

May I suggest having an info-bar near the top of the screen indicating what activity we currently have selected. Here are two mockups of what that might look like:

http://i.imgur.com/4rvzqzD.png
http://i.imgur.com/tbT3iO7.png

In the first mockup, I've added an exit icon which would exit the selected activity and go back to the default.

cc: @johnvanbreda

**Comment by charlesroper** [comment]
Further suggestion: tapping on the bar (not on the x to the right) could bring up the activity selection page (i.e., same at tapping the people icon at the top). I'm not massively wedded to this idea, but it sort of feels like it would be expected behaviour now that I look at the mockups a couple of days later). Thoughts?

**Comment by kazlauskis** [comment]
Yes, I quite like that. I am not sure if the X should quit the current activity or just hide the message, but I think it is a good idea to indicate that the user is recording with an activity.

Thanks!

**Comment by johnvanbreda** [comment]
Agreed. Given that the x is ambiguous, perhaps the version without the x is preferable?
Karolis - are you going to pick up this requirement?

**Comment by charlesroper** [comment]
Yes, I agree the X seems like it should dismiss the bar rather than "close" the selected activity. Maybe use the word "SWITCH" instead of an X? This is currently what Google's Material system encourages (flat button style):

https://www.google.com/design/spec/components/buttons.html#buttons-flat-buttons

Firefox on Android uses info bars similarly: http://i.imgur.com/pgFF1Te.png (at the bottom). Not sure if that's a no-no on iOS, though. My feeling is that there should be some sort of indication that the bar is a tap-target (if it is indeed to be a tap-target).

I've just demonstrated the activities feature to a few people here and they noted (without any prompting from me) that the UI needs an indication of what activity you're currently "in".

**Comment by kazlauskis** [comment]
Cool, yes we would probably do it like a flat button, though I feel that it should be just a notification without any buttons. If we added anything on the right, then there would be three buttons in one corner, which I think is too much for small screens.

OK, lets add this in then. Would you be willing to do it?

**Comment by charlesroper** [comment]
I would, but I can't dedicate the time anytime soon - sorry. I am keen to start contributing at some point if I can, though!

**Comment by kazlauskis** [comment]
No worries, I am working on something else now, but I will do this once I find some time then.
