### ISSUE TITLE
Common Nettle-tap not in App species list

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#89]
Can't find this species either by common or latin name.

**Comment by grahamcheckley** [comment]
Just wondering how this was getting on.

**Comment by grahamcheckley** [comment]
I also noticed today that Cheilosia illustrata isn't on the app species list.

**Comment by kazlauskis** [comment]
Hi Graham,

Sorry, I was on a leave. I have to quickly deliver another app this week and once that is done I will look into the species list.

Thanks for the patience!
