### ISSUE TITLE
Logging in to a different account retains records from previous account

### ISSUE THREAD

**Issue by charlesroper** [NERC-CEH/irecord-app#90]
I've just logged out of my main account into an empty test account and I'm seeing all of the records I submitted previously. Is this intentional? Shouldn't it only be showing records appropriate to the currently logged-in account?

**Comment by kazlauskis** [comment]
Heya, I see what you mean. Currently, all the unsubmitted records are sent to the current logged in user account, switching accounts would attach different user id to the records that reach the database. I feel that you would not want to wipe off unsent records by switching accounts, but as you say it is a different case with the submitted ones. 

I agree, the app should remove them once you have logged out.

**Comment by grahamcheckley** [comment]
I tried changing the account today in the app to demonstrate the functionality.  I signed out of my grahamcheckley account after clearing out the records and locations and then signed in to the FofBBVP account and entered a record.  On sending the record it went to my account not theirs.  A bug?

**Comment by kazlauskis** [comment]
Hi Graham, I have just checked this myself and can confirm it is a bug. Thanks!
