### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-app#98]
Show a simple statistics page.

![screen shot 2016-08-02 at 10 16 28](https://cloud.githubusercontent.com/assets/7383162/17323464/3b172dd2-589a-11e6-9b34-d1fd644df3b0.png)

**Comment by grahamcheckley** [comment]
I'd suggest that this be added to the main iRecord system rather than the app.  There is already a similar app statistics page there.
