### ISSUE TITLE
c20 lost records from an IOS submission

### ISSUE THREAD

**Issue by grahamcheckley** [NERC-CEH/irecord-app#99]
A colleague has reported loosing c20 records from his IOS mobile phone on Sunday 14th August.

The records should all be dated 13/08/2016, with a submission date of 14/08/2016 at about 15:05.  Recorder Bennet, Bruce.  Only one record, 3862722, appears to have made it on to iRecord.

Could you please check this out?

Best regards
Graham

**Comment by kazlauskis** [comment]
Thanks, I am looking into this now.

**Comment by kazlauskis** [comment]
Another one [here](http://www.brc.ac.uk/irecord/node/4487#comment-2238):

> I have been using the mobile app for a while and generally have no problem in uploading the records from the app onto the main irecord website.  However, I have nearly thirty records on my app dating from 25 March - 3rd April, which are showing as sent i.e. with the green arrow - but which are not appearing on the website.  I have tried logging off and on again both on the mobile app and on the website and have also tried sending them again via the 'submit all' button but to no avail.

**Comment by kazlauskis** [comment]
Closing this one due to its age.
